// Curated from Genetics_Hub_Combined_Test_List.xlsx (13,748 rows, 7 partner
// labs: AMPATH, Metropolis, Redcliffe, Tata 1mg, MedGenome, Yoda
// Diagnostics, Lilac Insights) — narrowed to the ~25 consumer-relevant
// genetic/specialty tests (prenatal screening, newborn screening, carrier
// screening, hereditary cancer, exome/genome/karyotype/microarray), each
// backed by real per-partner price + test code from that file. Deliberately
// sparse: only the partners that actually offer a given test are listed —
// not every test is done by every partner (see AGENTS' note in chat about
// genetics-specific tests). `testCode` is admin-only, never customer-facing.
//
// Naming note: different partners brand the same clinical test differently
// (e.g. Redcliffe's "Combined Screening" = Double Marker Test; MedGenome's
// "Claria-NIPT" = NIPT) — each entry below is filed under one canonical
// name/slug with the partner's real branded row attached, resolving exactly
// that kind of naming mismatch instead of listing them as separate tests.

export type PartnerPrice = { labSlug: string; price: number; mrp: number; testCode: string };

export type GeneticProductSeed = {
  slug: string;
  name: string;
  type: "TEST" | "PACKAGE";
  category: string;
  parameters: number;
  sampleType: string;
  fasting: boolean;
  reportHours: number;
  minAge?: number;
  gender?: "male" | "female" | "both";
  description: string;
  about: string;
  includes: string[];
  popular?: boolean;
  badge?: string;
  jghPrice: number;
  jghMrp: number;
  partners: PartnerPrice[];
};

export const GENETIC_PRODUCTS: GeneticProductSeed[] = [
  // ── Prenatal screening ────────────────────────────────────────────
  {
    slug: "nipt-non-invasive-prenatal-testing",
    name: "NIPT (Non-Invasive Prenatal Testing)",
    type: "TEST",
    category: "pregnancy",
    parameters: 3,
    sampleType: "Blood",
    fasting: false,
    reportHours: 216, // ~9 days
    gender: "female",
    description: "A blood-based prenatal screen for Down syndrome and other common chromosomal conditions — no risk to the pregnancy.",
    about:
      "NIPT analyses fragments of fetal DNA present in the mother's blood to screen for Down syndrome (Trisomy 21), Edward's syndrome (Trisomy 18) and Patau syndrome (Trisomy 13) with much higher accuracy than standard marker tests, and with zero risk to the pregnancy since it's just a blood draw. Usually done from week 10 onwards. It's a screening test, not diagnostic — a higher-risk result is followed by a diagnostic test like amniocentesis. Different labs sell this under different brand names (e.g. Claria-NIPT, NIPT TriSure) — same underlying test.",
    includes: ["Trisomy 21 (Down syndrome)", "Trisomy 18 (Edward's syndrome)", "Trisomy 13 (Patau syndrome)"],
    popular: true,
    jghPrice: 4499,
    jghMrp: 8500,
    partners: [
      { labSlug: "lilac-insights", price: 5000, mrp: 5000, testCode: "T111" },
      { labSlug: "medgenome", price: 7859, mrp: 7859, testCode: "MGM1528" },
      { labSlug: "metropolis", price: 12000, mrp: 12000, testCode: "G812" },
      { labSlug: "redcliffe-labs", price: 12200, mrp: 12200, testCode: "MD115" },
      { labSlug: "yoda-diagnostics", price: 15000, mrp: 15000, testCode: "FM003" },
      { labSlug: "ampath", price: 16000, mrp: 16000, testCode: "MD0260" },
    ],
  },
  {
    slug: "nipt-expanded-microdeletions",
    name: "NIPT — Expanded (All Chromosomes + Microdeletions)",
    type: "TEST",
    category: "pregnancy",
    parameters: 5,
    sampleType: "Blood",
    fasting: false,
    reportHours: 240,
    gender: "female",
    description: "A wider NIPT panel screening all 23 chromosome pairs plus common microdeletion syndromes, not just the 3 major trisomies.",
    about:
      "The expanded version of NIPT — beyond Down/Edward's/Patau syndrome, this also screens the remaining chromosomes and common microdeletion syndromes (small missing pieces of a chromosome, like DiGeorge syndrome) that the basic panel doesn't cover. Recommended when there's a specific risk factor, family history, or simply for the most thorough screen available from a blood draw. Still a screening test — a higher-risk result needs diagnostic confirmation.",
    includes: ["All 23 chromosome pairs", "Common microdeletion syndromes", "Fetal sex (optional)"],
    jghPrice: 7499,
    jghMrp: 14000,
    partners: [
      { labSlug: "lilac-insights", price: 10000, mrp: 10000, testCode: "T112" },
      { labSlug: "medgenome", price: 7859, mrp: 7859, testCode: "MGM1842" },
      { labSlug: "metropolis", price: 19260, mrp: 19260, testCode: "RD1492T" },
      { labSlug: "yoda-diagnostics", price: 20000, mrp: 20000, testCode: "FM004" },
      { labSlug: "ampath", price: 20000, mrp: 20000, testCode: "MD0290" },
      { labSlug: "redcliffe-labs", price: 22500, mrp: 22500, testCode: "MD116" },
    ],
  },
  {
    slug: "double-marker-test",
    name: "Double Marker Test",
    type: "TEST",
    category: "pregnancy",
    parameters: 2,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    gender: "female",
    description: "A first-trimester blood test that screens for Down syndrome and other chromosomal conditions, usually paired with an NT ultrasound scan.",
    about:
      "The Double Marker Test measures two blood markers (free beta-hCG and PAPP-A) between weeks 11–13 of pregnancy, combined with the NT (nuchal translucency) ultrasound scan, to assess the risk of Down syndrome and other chromosomal conditions. It's a screening test, not diagnostic. Redcliffe Labs sells this same test under the brand name \"Combined Screening.\"",
    includes: ["Free Beta-hCG", "PAPP-A"],
    popular: true,
    jghPrice: 1499,
    jghMrp: 3000,
    partners: [
      { labSlug: "yoda-diagnostics", price: 1700, mrp: 1700, testCode: "BCG080" },
      { labSlug: "tata-1mg", price: 1729, mrp: 1729, testCode: "LFSIM58GUR" },
      { labSlug: "redcliffe-labs", price: 2100, mrp: 2100, testCode: "BC480B" }, // sold as "Combined Screening- Roche (Astraia)"
      { labSlug: "metropolis", price: 2650, mrp: 2650, testCode: "1268D" },
      { labSlug: "ampath", price: 2750, mrp: 2750, testCode: "BC0867" },
    ],
  },
  {
    slug: "triple-marker-test",
    name: "Triple Marker Test",
    type: "TEST",
    category: "pregnancy",
    parameters: 3,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    gender: "female",
    description: "A second-trimester screening test assessing risk of Down syndrome, Edward's syndrome and neural tube defects.",
    about:
      "The Triple Marker Test measures AFP, hCG and estriol (uE3) between weeks 15–20, used to assess risk of Down syndrome, Edward's syndrome and neural tube defects (like spina bifida) when a first-trimester screen wasn't done or as an additional check.",
    includes: ["AFP", "hCG", "Estriol (uE3)"],
    jghPrice: 999,
    jghMrp: 2200,
    partners: [
      { labSlug: "medgenome", price: 1123, mrp: 1123, testCode: "MGM2469" },
      { labSlug: "yoda-diagnostics", price: 2300, mrp: 2300, testCode: "BCG160" },
      { labSlug: "lilac-insights", price: 2500, mrp: 2500, testCode: "G03S07T06" },
      { labSlug: "tata-1mg", price: 2610, mrp: 2610, testCode: "LFSIM173GUR" },
      { labSlug: "redcliffe-labs", price: 2799, mrp: 2799, testCode: "BC070" },
      { labSlug: "ampath", price: 3200, mrp: 3200, testCode: "BC01000" },
    ],
  },
  {
    slug: "quadruple-marker-test",
    name: "Quadruple Marker Test",
    type: "TEST",
    category: "pregnancy",
    parameters: 4,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    gender: "female",
    description: "A second-trimester screen for Down syndrome and neural tube defects — an expanded version of the triple marker test with one extra marker for better accuracy.",
    about:
      "The Quadruple Marker Test is a second-trimester prenatal screening test (ideally done between weeks 15–20) that measures four blood markers to assess the risk of Down syndrome, Edward's syndrome and open neural tube defects. It's a screening test, not diagnostic — a higher-risk result is typically followed by further diagnostic tests like amniocentesis.",
    includes: ["AFP", "hCG", "Estriol", "Inhibin-A"],
    jghPrice: 1899,
    jghMrp: 4200,
    partners: [
      { labSlug: "yoda-diagnostics", price: 2800, mrp: 2800, testCode: "BCG147" },
      { labSlug: "tata-1mg", price: 2970, mrp: 2970, testCode: "LFSIM137GUR" },
      { labSlug: "lilac-insights", price: 3000, mrp: 3000, testCode: "G03S07T05" },
      { labSlug: "metropolis", price: 3300, mrp: 3300, testCode: "1275P" },
      { labSlug: "redcliffe-labs", price: 3299, mrp: 3299, testCode: "BC248" },
      { labSlug: "ampath", price: 4200, mrp: 4200, testCode: "PR1059" },
    ],
  },
  {
    slug: "pgt-a-preimplantation-aneuploidy",
    name: "PGT-A (Preimplantation Genetic Testing — Aneuploidy)",
    type: "TEST",
    category: "pregnancy",
    parameters: 1,
    sampleType: "Embryo Biopsy",
    fasting: false,
    reportHours: 336,
    gender: "female",
    description: "Screens IVF embryos for the correct number of chromosomes before transfer, to help choose the embryo most likely to succeed.",
    about:
      "PGT-A screens embryos created via IVF for chromosomal abnormalities (an incorrect number of chromosomes) before one is transferred, helping select the embryo with the best chance of a successful, healthy pregnancy and reducing miscarriage risk. Price shown is the starting per-embryo rate — the fertility clinic/lab quotes the final price based on how many embryos are tested.",
    includes: ["Chromosome count per embryo"],
    jghPrice: 5499,
    jghMrp: 12000,
    partners: [
      { labSlug: "medgenome", price: 6045, mrp: 6045, testCode: "MGM1737" },
      { labSlug: "lilac-insights", price: 20000, mrp: 20000, testCode: "G05S06T13" },
      { labSlug: "metropolis", price: 14980, mrp: 14980, testCode: "RD1522" },
    ],
  },
  {
    slug: "pgt-m-preimplantation-monogenic",
    name: "PGT-M (Preimplantation Genetic Testing — Monogenic)",
    type: "TEST",
    category: "pregnancy",
    parameters: 1,
    sampleType: "Embryo Biopsy",
    fasting: false,
    reportHours: 336,
    gender: "female",
    description: "Screens IVF embryos for a specific known single-gene disorder that runs in the family, before transfer.",
    about:
      "PGT-M screens IVF embryos for one specific inherited single-gene condition already known to run in the family (e.g. thalassemia, SMA), so only embryos unaffected by that condition are considered for transfer. Requires prior genetic workup of the parents to identify the exact variant being tested for. Pricing is highly individualized (depends on the condition, number of embryos, and whether parental reference samples are needed) — the price shown is a representative starting point; the lab will quote the exact figure after reviewing your case.",
    includes: ["Targeted single-gene variant analysis per embryo"],
    jghPrice: 24999,
    jghMrp: 55000,
    partners: [
      { labSlug: "lilac-insights", price: 25000, mrp: 25000, testCode: "G05S06T33" },
      { labSlug: "medgenome", price: 87314, mrp: 87314, testCode: "MGM1732" },
    ],
  },

  // ── Newborn & child screening ─────────────────────────────────────
  {
    slug: "newborn-screening-panel",
    name: "Newborn Screening Panel",
    type: "PACKAGE",
    category: "child-care",
    parameters: 50,
    sampleType: "Blood (Heel Prick)",
    fasting: false,
    reportHours: 168,
    minAge: 0,
    description: "Early screening for treatable congenital disorders in newborns — thyroid, metabolic and enzyme conditions.",
    about:
      "Newborn screening checks a few drops of blood (usually a heel-prick sample, taken 48-72 hours after birth) for a panel of rare but serious congenital conditions — thyroid deficiency, metabolic disorders, G6PD deficiency, CAH and others — that show no symptoms at birth but are far more manageable when caught in the first weeks of life rather than found later. Panels vary by lab from a basic handful of conditions up to 50+.",
    includes: ["Congenital Hypothyroidism (TSH)", "CAH (17-OHP)", "G6PD Deficiency", "Galactosemia", "Biotinidase", "Phenylketonuria (PKU)"],
    popular: true,
    badge: "For Newborns",
    jghPrice: 2499,
    jghMrp: 6000,
    partners: [
      { labSlug: "tata-1mg", price: 2469, mrp: 2469, testCode: "1MGST0007" },
      { labSlug: "ampath", price: 2700, mrp: 2700, testCode: "BC0265" },
      { labSlug: "yoda-diagnostics", price: 5000, mrp: 5000, testCode: "BCG001" },
      { labSlug: "metropolis", price: 5995, mrp: 5995, testCode: "3328IJ" },
      { labSlug: "medgenome", price: 7945, mrp: 7945, testCode: "MGM2705" },
    ],
  },
  {
    slug: "g6pd-deficiency-screening",
    name: "G6PD Deficiency Screening",
    type: "TEST",
    category: "child-care",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    minAge: 0,
    description: "Checks for G6PD enzyme deficiency, a common inherited condition that can cause serious jaundice or anaemia in newborns triggered by certain foods, infections or medicines.",
    about:
      "G6PD deficiency is one of the most common inherited enzyme conditions worldwide — it doesn't usually cause problems day-to-day, but can trigger sudden jaundice or anaemia in a newborn or child when exposed to certain triggers (fava beans, some infections, and specific medicines including some antibiotics). This quantitative blood test measures enzyme activity to confirm or rule out deficiency, commonly done as part of newborn screening or when unexplained jaundice/anaemia comes up.",
    includes: ["G6PD Enzyme Activity"],
    jghPrice: 599,
    jghMrp: 1400,
    partners: [
      { labSlug: "tata-1mg", price: 809, mrp: 809, testCode: "1MGHA0005" },
      { labSlug: "redcliffe-labs", price: 900, mrp: 900, testCode: "BC163" },
      { labSlug: "metropolis", price: 1150, mrp: 1150, testCode: "1146QT" },
      { labSlug: "lilac-insights", price: 1200, mrp: 1200, testCode: "T108" },
      { labSlug: "ampath", price: 1300, mrp: 1300, testCode: "BC0122" },
    ],
  },

  // ── Cancer Screening ───────────────────────────────────────────────
  {
    slug: "brca1-brca2-gene-analysis",
    name: "BRCA1 & BRCA2 Gene Analysis",
    type: "TEST",
    category: "cancer-screening",
    parameters: 2,
    sampleType: "Blood",
    fasting: false,
    reportHours: 288,
    description: "Checks for inherited BRCA1/BRCA2 gene changes linked to a significantly higher lifetime risk of breast and ovarian cancer.",
    about:
      "BRCA1 and BRCA2 are genes that normally help repair damaged DNA; an inherited harmful change in either significantly raises lifetime risk of breast, ovarian, and some other cancers. This test is typically recommended for those with a strong family history of breast/ovarian cancer, a relative with a known BRCA mutation, or certain cancer diagnoses at a young age. A positive result doesn't mean cancer is certain — it informs earlier/more frequent screening and risk-reduction options with a genetic counsellor or oncologist.",
    includes: ["BRCA1 gene analysis", "BRCA2 gene analysis"],
    popular: true,
    jghPrice: 4999,
    jghMrp: 12000,
    partners: [
      { labSlug: "medgenome", price: 5614, mrp: 5614, testCode: "MGM178" },
      { labSlug: "tata-1mg", price: 12730, mrp: 12730, testCode: "1MGMB0076" },
      { labSlug: "redcliffe-labs", price: 14000, mrp: 14000, testCode: "MD321" },
      { labSlug: "yoda-diagnostics", price: 14000, mrp: 14000, testCode: "MOL008" },
      { labSlug: "metropolis", price: 16500, mrp: 16500, testCode: "G813" },
      { labSlug: "lilac-insights", price: 22000, mrp: 22000, testCode: "T92" },
      { labSlug: "ampath", price: 22000, mrp: 22000, testCode: "MD0279" },
    ],
  },
  {
    slug: "hereditary-cancer-gene-panel",
    name: "Hereditary Cancer Gene Panel",
    type: "PACKAGE",
    category: "cancer-screening",
    parameters: 30,
    sampleType: "Blood",
    fasting: false,
    reportHours: 336,
    description: "A broader multi-gene panel (beyond just BRCA1/2) screening for inherited mutations linked to several hereditary cancer syndromes at once.",
    about:
      "Rather than checking just BRCA1/2, this panel screens dozens of genes linked to hereditary breast, ovarian, colorectal, pancreatic and other cancer syndromes in one test — useful when family history suggests an inherited cancer risk but doesn't point to one specific gene. Usually recommended alongside genetic counselling, since results can be complex to interpret.",
    includes: ["30+ hereditary cancer-risk genes", "Includes BRCA1 & BRCA2"],
    jghPrice: 4499,
    jghMrp: 11000,
    partners: [
      { labSlug: "medgenome", price: 4923, mrp: 4923, testCode: "MGM194" },
      { labSlug: "tata-1mg", price: 17860, mrp: 17860, testCode: "1MGOTH0002" },
      { labSlug: "ampath", price: 18000, mrp: 18000, testCode: "MD0651" },
      { labSlug: "redcliffe-labs", price: 20000, mrp: 20000, testCode: "MD323" },
      { labSlug: "metropolis", price: 23540, mrp: 23540, testCode: "G560" },
    ],
  },

  // ── Genetic Testing (specialty) ────────────────────────────────────
  {
    slug: "whole-exome-sequencing",
    name: "Whole Exome Sequencing (WES)",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 360,
    description: "Reads the protein-coding portion of your entire genome (~20,000 genes) — the broadest single test for diagnosing an unexplained genetic condition.",
    about:
      "Whole Exome Sequencing reads the ~1-2% of your DNA that codes for proteins (where the large majority of known disease-causing variants are found) across roughly 20,000 genes at once. It's typically used when a child or adult has symptoms suggestive of a genetic condition but no specific gene is suspected — a single broad test instead of ordering many individual gene tests one at a time. Results are interpreted by a geneticist and usually take 2-4 weeks.",
    includes: ["~20,000 protein-coding genes"],
    jghPrice: 11999,
    jghMrp: 28000,
    partners: [
      { labSlug: "medgenome", price: 13905, mrp: 13905, testCode: "MGM2572" },
      { labSlug: "tata-1mg", price: 33250, mrp: 33250, testCode: "1MGNGS168" },
    ],
  },
  {
    slug: "clinical-exome-sequencing",
    name: "Clinical Exome Sequencing (CES)",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 288,
    description: "A focused version of exome sequencing, analysing the ~5,000 genes with well-established links to known genetic diseases — faster and more affordable than the full exome.",
    about:
      "Clinical Exome Sequencing analyses a curated set of roughly 5,000 genes already known to cause disease (rather than all ~20,000 genes in a full exome), making it faster to interpret and generally more affordable while still covering the genes most likely to explain a suspected genetic condition. Often the first choice before considering a full Whole Exome or Genome test.",
    includes: ["~5,000 clinically-relevant genes"],
    popular: true,
    jghPrice: 8499,
    jghMrp: 19000,
    partners: [
      { labSlug: "medgenome", price: 9241, mrp: 9241, testCode: "MGM272" },
      { labSlug: "redcliffe-labs", price: 17400, mrp: 17400, testCode: "MD315" },
      { labSlug: "yoda-diagnostics", price: 20000, mrp: 20000, testCode: "MOL057" },
      { labSlug: "tata-1mg", price: 21470, mrp: 21470, testCode: "1MGNGS117" },
      { labSlug: "ampath", price: 23000, mrp: 23000, testCode: "MD0409" },
      { labSlug: "metropolis", price: 23540, mrp: 23540, testCode: "RD1544" },
      { labSlug: "lilac-insights", price: 25000, mrp: 25000, testCode: "G05S02T01" },
    ],
  },
  {
    slug: "whole-genome-sequencing",
    name: "Whole Genome Sequencing (WGS)",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 504,
    description: "Reads essentially all of your DNA, coding and non-coding — the most complete genetic test available, used when exome sequencing hasn't found an answer.",
    about:
      "Whole Genome Sequencing reads virtually all of your DNA — not just the protein-coding exome but the regulatory and non-coding regions too — giving the most complete picture available. It's the most expensive and data-intensive option, generally used when a strong clinical suspicion of a genetic condition remains after exome sequencing didn't find a clear answer, or for specific research/comprehensive-screening purposes.",
    includes: ["Full genome — coding and non-coding regions"],
    badge: "Most Comprehensive",
    jghPrice: 64999,
    jghMrp: 140000,
    partners: [
      { labSlug: "medgenome", price: 69955, mrp: 69955, testCode: "MGM275" },
      { labSlug: "lilac-insights", price: 100000, mrp: 100000, testCode: "G06S03T21" },
      { labSlug: "ampath", price: 125000, mrp: 125000, testCode: "MD0623" },
      { labSlug: "metropolis", price: 128400, mrp: 128400, testCode: "G585" },
    ],
  },
  {
    slug: "karyotyping-blood",
    name: "Karyotyping (Blood)",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 240,
    description: "Examines the number and structure of your chromosomes under a microscope — used to diagnose chromosomal conditions like Down syndrome, or investigate infertility and recurrent miscarriage.",
    about:
      "Karyotyping is the classic chromosome test: a blood sample's cells are cultured and the chromosomes examined under a microscope for the correct count (46) and structure. It's used to confirm chromosomal conditions like Down syndrome, investigate unexplained infertility or recurrent miscarriage in a couple, or check for chromosomal rearrangements. Takes longer than most tests since it requires growing living cells in culture first.",
    includes: ["Chromosome count", "Chromosome structure (G-banding)"],
    jghPrice: 1799,
    jghMrp: 4200,
    partners: [
      { labSlug: "medgenome", price: 777, mrp: 777, testCode: "MGM575" },
      { labSlug: "yoda-diagnostics", price: 2000, mrp: 2000, testCode: "CYTO002" },
      { labSlug: "redcliffe-labs", price: 2500, mrp: 2500, testCode: "CG050" },
      { labSlug: "tata-1mg", price: 2880, mrp: 2880, testCode: "LFSMB28GUR" },
      { labSlug: "ampath", price: 4200, mrp: 4200, testCode: "CG0016" },
      { labSlug: "lilac-insights", price: 5500, mrp: 5500, testCode: "G09S11T05" },
    ],
  },
  {
    slug: "karyotyping-prenatal",
    name: "Karyotyping (Prenatal)",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Amniotic Fluid / CVS",
    fasting: false,
    reportHours: 288,
    gender: "female",
    description: "Chromosome analysis on a prenatal sample (amniotic fluid or CVS) — a diagnostic test, unlike NIPT or marker screening which only estimate risk.",
    about:
      "Prenatal Karyotyping examines fetal chromosomes directly from a sample obtained via amniocentesis or CVS (chorionic villus sampling), giving a definitive diagnosis of chromosomal conditions rather than a risk estimate like NIPT or marker screening. Usually done as a follow-up when a screening test comes back higher-risk, since amniocentesis/CVS themselves carry a small procedural risk that a blood-based screen doesn't.",
    includes: ["Fetal chromosome count", "Fetal chromosome structure"],
    jghPrice: 3999,
    jghMrp: 9000,
    partners: [
      { labSlug: "medgenome", price: 1900, mrp: 1900, testCode: "MGM1647" },
      { labSlug: "redcliffe-labs", price: 4800, mrp: 4800, testCode: "CG035" },
      { labSlug: "ampath", price: 12000, mrp: 12000, testCode: "CG0107" },
    ],
  },
  {
    slug: "chromosomal-microarray-prenatal",
    name: "Chromosomal Microarray (Prenatal)",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Amniotic Fluid / CVS",
    fasting: false,
    reportHours: 288,
    gender: "female",
    description: "A higher-resolution alternative to karyotyping that can detect much smaller chromosomal changes too small for a microscope to see.",
    about:
      "Chromosomal Microarray scans for gains or losses of genetic material at a much finer resolution than traditional karyotyping — it can detect small microdeletions/microduplications that a microscope-based karyotype would miss entirely. Increasingly used as a first-line prenatal diagnostic test (after amniocentesis/CVS) alongside or instead of karyotyping, especially when an ultrasound finding raises concern.",
    includes: ["Genome-wide copy number analysis"],
    jghPrice: 10999,
    jghMrp: 24000,
    partners: [
      { labSlug: "redcliffe-labs", price: 12300, mrp: 12300, testCode: "MD313" },
      { labSlug: "medgenome", price: 13300, mrp: 13300, testCode: "MGM294" },
      { labSlug: "tata-1mg", price: 14250, mrp: 14250, testCode: "1MGCI0011" },
      { labSlug: "metropolis", price: 17655, mrp: 17655, testCode: "6042M" },
      { labSlug: "yoda-diagnostics", price: 22000, mrp: 22000, testCode: "CYTO022" },
    ],
  },
  {
    slug: "carrier-screening-focused",
    name: "Carrier Screening — Focused Panel",
    type: "PACKAGE",
    category: "genetic-testing",
    parameters: 100,
    sampleType: "Blood / Saliva",
    fasting: false,
    reportHours: 288,
    description: "Checks whether you carry (without symptoms yourself) a gene change for common inherited conditions that could affect your children.",
    about:
      "Carrier screening checks whether you silently carry a gene variant for a recessive inherited condition — you'd show no symptoms yourself, but if your partner carries a variant in the same gene, each pregnancy has a real chance of the child being affected. This focused panel covers around 100 of the more common conditions. Best done before or early in pregnancy, ideally alongside your partner, so you have time to understand and act on the results.",
    includes: ["~100-gene recessive-condition panel"],
    jghPrice: 10999,
    jghMrp: 26000,
    partners: [
      { labSlug: "medgenome", price: 12782, mrp: 12782, testCode: "MGM429" },
      { labSlug: "metropolis", price: 25000, mrp: 25000, testCode: "G637" },
    ],
  },
  {
    slug: "carrier-screening-expanded",
    name: "Carrier Screening — Expanded Panel (NGS)",
    type: "PACKAGE",
    category: "genetic-testing",
    parameters: 500,
    sampleType: "Blood / Saliva",
    fasting: false,
    reportHours: 336,
    description: "A much wider carrier screen (hundreds of genes by NGS) for couples planning a pregnancy who want the most thorough check available.",
    about:
      "The expanded version of carrier screening — using next-generation sequencing to check several hundred genes at once (including conditions like SMA, thalassemia and Fragile X) instead of ~100. The most thorough carrier-screening option available, typically chosen by couples who want the broadest possible check before or during pregnancy, or who have a family history that doesn't point to one specific condition.",
    includes: ["500+ gene NGS recessive-condition panel", "Includes SMA & CYP21A2"],
    jghPrice: 22999,
    jghMrp: 55000,
    partners: [
      { labSlug: "medgenome", price: 25391, mrp: 25391, testCode: "MGM1000" },
      { labSlug: "redcliffe-labs", price: 30700, mrp: 30700, testCode: "MD176" },
      { labSlug: "metropolis", price: 32000, mrp: 32000, testCode: "G616" },
      { labSlug: "lilac-insights", price: 70000, mrp: 70000, testCode: "G05S08T09" },
    ],
  },
  {
    slug: "alpha-thalassemia-mutation-analysis",
    name: "Alpha Thalassemia Mutation Analysis",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    description: "A definitive genetic test for alpha thalassemia — confirms the diagnosis and specific gene deletion/mutation, beyond what a routine HPLC screen shows.",
    about:
      "While a Hemoglobin HPLC test screens for signs of thalassemia, this test looks directly at the HBA1/HBA2 genes to confirm alpha thalassemia and identify the specific deletion or mutation involved — important for genetic counselling, family planning, and confirming a diagnosis suggested by other tests or a family history.",
    includes: ["HBA1 gene analysis", "HBA2 gene analysis"],
    jghPrice: 3799,
    jghMrp: 8500,
    partners: [
      { labSlug: "metropolis", price: 4280, mrp: 4280, testCode: "2479" },
      { labSlug: "redcliffe-labs", price: 4300, mrp: 4300, testCode: "MD117" },
      { labSlug: "ampath", price: 5500, mrp: 5500, testCode: "HM0144" },
      { labSlug: "medgenome", price: 6995, mrp: 6995, testCode: "MGM040" },
      { labSlug: "lilac-insights", price: 10000, mrp: 10000, testCode: "G08S20T06" },
    ],
  },
  {
    slug: "beta-thalassemia-mutation-analysis",
    name: "Beta Thalassemia Mutation Analysis",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    description: "A definitive genetic test for beta thalassemia — confirms the diagnosis and specific gene mutation, important for family planning and genetic counselling.",
    about:
      "Beta thalassemia is one of the most common inherited blood disorders in India. This test looks directly at the HBB gene for the mutations that cause it, confirming a diagnosis suggested by a Hemoglobin HPLC screen, identifying carriers, and informing genetic counselling for couples planning a pregnancy where thalassemia runs in the family.",
    includes: ["HBB gene mutation analysis (common mutations panel)"],
    popular: true,
    jghPrice: 3999,
    jghMrp: 9000,
    partners: [
      { labSlug: "redcliffe-labs", price: 5200, mrp: 5200, testCode: "MD003" },
      { labSlug: "medgenome", price: 4664, mrp: 4664, testCode: "MGM044" },
      { labSlug: "ampath", price: 7200, mrp: 7200, testCode: "MD0234" },
      { labSlug: "yoda-diagnostics", price: 7000, mrp: 7000, testCode: "MOL093" },
      { labSlug: "lilac-insights", price: 7500, mrp: 7500, testCode: "G06S02T14" },
      { labSlug: "metropolis", price: 7490, mrp: 7490, testCode: "2482" },
    ],
  },
  {
    slug: "fragile-x-syndrome-testing",
    name: "Fragile X Syndrome Testing",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    description: "Checks for the FMR1 gene change that causes Fragile X syndrome, the most common inherited cause of intellectual disability.",
    about:
      "Fragile X syndrome is caused by an expansion in the FMR1 gene and is the most common inherited cause of intellectual disability and autism spectrum features. This test is typically done for a child with developmental delay of unknown cause, or for carrier screening in someone with a family history of Fragile X, intellectual disability, or early menopause/ovarian issues (which can also be linked to FMR1 carrier status).",
    includes: ["FMR1 gene analysis (CGG repeat expansion)"],
    jghPrice: 3999,
    jghMrp: 9500,
    partners: [
      { labSlug: "yoda-diagnostics", price: 4500, mrp: 4500, testCode: "MOL022" },
      { labSlug: "ampath", price: 7500, mrp: 7500, testCode: "MD0215" },
      { labSlug: "metropolis", price: 7815, mrp: 7815, testCode: "RD1325" },
      { labSlug: "medgenome", price: 8377, mrp: 8377, testCode: "MGM1221" },
      { labSlug: "redcliffe-labs", price: 8100, mrp: 8100, testCode: "MD025" },
      { labSlug: "tata-1mg", price: 9975, mrp: 9975, testCode: "1MGOTH0090" },
    ],
  },
  {
    slug: "spinal-muscular-atrophy-testing",
    name: "Spinal Muscular Atrophy (SMA) Testing",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    description: "Checks for the SMN1 gene deletion that causes Spinal Muscular Atrophy, a serious inherited condition affecting muscle strength and movement.",
    about:
      "Spinal Muscular Atrophy is a serious inherited condition affecting the nerve cells that control muscles, caused by a missing or altered SMN1 gene. This test detects that deletion — used both for diagnosing a child with symptoms (muscle weakness, delayed motor milestones) and for carrier screening in adults planning a pregnancy, since roughly 1 in 50 people are carriers without knowing it.",
    includes: ["SMN1 gene deletion/duplication analysis"],
    jghPrice: 2799,
    jghMrp: 6500,
    partners: [
      { labSlug: "metropolis", price: 3000, mrp: 3000, testCode: "8764" },
      { labSlug: "medgenome", price: 3023, mrp: 3023, testCode: "MGM143" },
      { labSlug: "ampath", price: 3700, mrp: 3700, testCode: "MD0032" },
      { labSlug: "redcliffe-labs", price: 6700, mrp: 6700, testCode: "MD085" },
      { labSlug: "tata-1mg", price: 5700, mrp: 5700, testCode: "1MGPS1068" },
    ],
  },
  {
    slug: "cystic-fibrosis-cftr-testing",
    name: "Cystic Fibrosis (CFTR) Gene Testing",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    description: "Checks the CFTR gene for mutations that cause Cystic Fibrosis, an inherited condition mainly affecting the lungs and digestion.",
    about:
      "Cystic Fibrosis is caused by mutations in the CFTR gene and mainly affects the lungs and digestive system. This test looks for the most common disease-causing mutations (including Delta F508, the most frequent one worldwide) — used to diagnose a child with suggestive symptoms (like recurrent chest infections or poor weight gain), confirm a positive newborn screen, or check carrier status before a pregnancy.",
    includes: ["CFTR gene mutation panel"],
    jghPrice: 3999,
    jghMrp: 9500,
    partners: [
      { labSlug: "redcliffe-labs", price: 4800, mrp: 4800, testCode: "MD309" },
      { labSlug: "tata-1mg", price: 6299, mrp: 6299, testCode: "LFSMB35GUR" },
      { labSlug: "medgenome", price: 7341, mrp: 7341, testCode: "MGM064" },
      { labSlug: "lilac-insights", price: 9000, mrp: 9000, testCode: "G06S04T24" },
      { labSlug: "ampath", price: 13000, mrp: 13000, testCode: "MD0030" },
      { labSlug: "metropolis", price: 13910, mrp: 13910, testCode: "RD1446" },
    ],
  },
  {
    slug: "congenital-adrenal-hyperplasia-gene-analysis",
    name: "Congenital Adrenal Hyperplasia (CAH) Gene Analysis",
    type: "TEST",
    category: "genetic-testing",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    minAge: 0,
    description: "Checks the CYP21A2 gene for mutations that cause Congenital Adrenal Hyperplasia, a condition often first picked up on newborn screening.",
    about:
      "Congenital Adrenal Hyperplasia (CAH) is an inherited condition affecting the adrenal glands' hormone production, most commonly caused by CYP21A2 gene mutations. It's often first flagged by a newborn screening panel; this gene-level test confirms the diagnosis and identifies the exact mutation, useful for the child's ongoing care and for carrier screening in future pregnancies.",
    includes: ["CYP21A2 gene analysis"],
    jghPrice: 2999,
    jghMrp: 7000,
    partners: [
      { labSlug: "medgenome", price: 3368, mrp: 3368, testCode: "MGM028" },
      { labSlug: "metropolis", price: 14980, mrp: 14980, testCode: "G513" },
      { labSlug: "redcliffe-labs", price: 20500, mrp: 20500, testCode: "MD187" },
      { labSlug: "yoda-diagnostics", price: 25000, mrp: 25000, testCode: "GEN061" },
      { labSlug: "lilac-insights", price: 25000, mrp: 25000, testCode: "G06S03T35" },
    ],
  },
];
