// Redcliffe Labs — oncology price list (Jan 2024, slab R2 MRP), parsed from the
// PDF shared by the business owner. Tuple: code, name, components, MRP (rupees),
// sample, method, turnaround hours (0 = not stated).
// Consumed by prisma/import-lab-catalogs.ts.
export type RedcliffeOncoRow = readonly [
  code: string,
  name: string,
  components: string,
  mrp: number,
  sample: string,
  method: string,
  tatHours: number,
];

export const REDCLIFFE_ONCOLOGY: RedcliffeOncoRow[] = [
  ["CG001","14q32.3 Gene Rearrangement (ALL, NHL) By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["CG064","17p (TP53) Deletion By FISH","",5000,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["CG002","1P/19Q By FISH","",9700,"Paraffin Embedded Tissue Blocks / FFPE","FISH",216],
  ["CG078","1p19q co-deletion, 1p3619q13 By FISH","",9200,"Paraffin Embedded Tissue Blocks","FISH",168],
  ["CG073","6q Deletion By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["HM026","Acute Leukemia Diagnostic Panel By Flowcytometry","",9700,"Whole Blood EDTA & 3ml Whole Blood Sodium Heparin / Bone Marrow Sodium Heparin","Flow Cytometry",96],
  ["HM110","Acute Leukemia MRD Panel","",10400,"Bone Marrow Sodium Heparin & Whole Blood Sodium Heparin","Flow Cytometry",96],
  ["CG057","Acute Lymphoblastic Leukemia (ALL) Panel By FISH","BCR-ABL1, TEL-AML1, MLL, E2A breakapart",13000,"Whole Blood Sodium Heparin / Bone Marrow","FISH",192],
  ["MD319","Acute Lymphoblastic Leukemia (ALL) Panel By PCR","",7900,"Whole Blood EDTA / Bone Marrow","Multiplex RT PCR",168],
  ["HM112","Acute Myeloid Leukemia (AML) MRD Panel By Flowcytometry","",12500,"Whole Blood Sodium Heparin / Bone Marrow","Flow Cytometry",96],
  ["CG004","Acute Myeloid Leukemia (AML) Panel By FISH","PML/RARA, AML1/ETO, inv(16)",14300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",192],
  ["MD001","Acute Myeloid Leukemia (AML) Panel By PCR","",7000,"Whole Blood EDTA / Bone Marrow","PCR",168],
  ["CG003","ALK Gene Rearrangements By FISH","",9600,"Paraffin Embedded Tissue Blocks / FFPE","FISH",216],
  ["MD489","ALK Resistance Mutations By NGS","",12000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",504],
  ["MD161","ALL Risk Stratification Gene Panel- B-ALL","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) /3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD162","ALL Risk Stratification Gene Panel- T-ALL","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["BC446","Alpha Fetoprotein (AFP), Tumor Marker","",900,"Serum in SST Yellow tube","Chemiluminescence (CLIA",4],
  ["MD166","AML Risk Stratification Gene Panel","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["CG005","AML/ETO t(8;21) By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG006","ATM Deletion 11q By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG007","BCL6 By FISH","",6500,"Whole Blood EDTA / Bone Marrow / Paraffin Embedded Tissue Blocks / FFPE","FISH",168],
  ["CG008","BCR ABL t(9:22) Philadelphia Chromosome By FISH","",4400,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["MD002","BCR ABL1 Kinase Domain Mutation Analysis (IRMA-Imatinib Resistance Mutation Analysis)","",8400,"Whole Blood EDTA","Real Time PCR",288],
  ["MD105","BRAF V600E Mutation","",7000,"Paraffin Embedded Tissue Blocks / FFPE ARMS","PCR",216],
  ["MD502","BRCA1 & BRCA2 Somatic Mutation","",20000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",672],
  ["PL135","Breast Cancer Basic CA 15.3, CEA","",2200,"Serum SST Yellow top Electrochemiluminescence (ECLIA) Same day","",0],
  ["BC011","CA 125 (Ovarian Cancer Marker)","",1300,"Serum SST Yellow top CLIA Same Day","",0],
  ["BC096","CA 15.3 (Breast Cancer Marker)","",1500,"Serum SST Yellow top ECLIA Same Day","",0],
  ["BC097","CA 19.9 (Pancreatic Cancer Marker)","",1500,"Serum SST Yellow top CMIA Same Day","",0],
  ["BC098","CA 72.4 (Gastric Cancer Marker)","",1600,"Serum SST Yellow top Electrochemiluminescence (ECLIA) Same Day (8 PM)","",0],
  ["MD106","Calreticulin (CALR) Mutation","",4900,"Whole Blood EDTA PCR Sequencing 7 Working Days PL115A Cancer Advance Package- Female CBC, HCG, CEA, CA 125, CA 15.3 R4 1499 3ml Whole Blood EDTA & 3ml Serum SST Yellow top Automated Cell Counter, CMIA, ECLIA 8 Hrs PL116A Cancer Advance Package- Male CBC, CEA, PSA Total, PSA Free, PSA Free/Total Ratio, CA 19.9 R4 1499 3ml Whole Blood EDTA & 3ml Serum SST Yellow top Automated Cell Counter, CMIA, ECLIA 8 Hrs PL115B Cancer Advance Profile- 2 (Female) CBC, HCG, CEA, CA 125, CA 15.3, CA 19.9 R4 1999 3ml Whole Blood EDTA & 3ml Serum SST Yellow top Automated Cell Counter, CMIA, CLIA Same Day","",0],
  ["PL115","Cancer Screening- Female CEA, CA 125, CA 15.3","",1199,"Serum SST Yellow top CMIA, E","CLIA",8],
  ["PL116","Cancer Screening- Male CEA, PSA Total, CA 19.9","",999,"Serum SST Yellow top CMIA, ECLIA 8 Hrs PL115C Cancer Screening Profile- 2 (Female) CEA, CA 125, CA 19.9 R4 1199 4ml Serum SST Yellow top CLIA, CMIA Same Day","",0],
  ["BC105","Carcinoembryonic Antigen (CEA)","",740,"Serum SST Yellow top CMIA Same Day","",0],
  ["HM031","CD19 By Flowcytometry","% CD 19 Cells, Absolute count CD 19 Cells",2200,"Whole Blood EDTA & 3ml Whole Blood Sodium Heparin / Bone Marrow Sodium Heparin","Flow Cytometry",48],
  ["HM104","CD20 By Flowcytometry","",2200,"Whole Blood EDTA & Whole Blood Sodium Heparin / Bone Marrow Sodium Heparin","Flow Cytometry",48],
  ["HM005","CD3, CD4 & CD8 By Flowcytometry","ALC, CD3 (Total T cells), Absolute CD3, CD4 (Helper T cells), Absolute CD4, CD8 (Suppressor T cells), Absolute CD8, CD4 / CD8 Ratio",2600,"Whole Blood EDTA Flow Cytometry Next Working Day","",0],
  ["HM032","CD4 & CD8 By Flowcytometry","ALC, CD4 (Helper T cells), Absolute CD4, CD8 (Suppressor T cells), Absolute CD8, CD4 / CD8 Ratio",1800,"Whole Blood EDTA & 3ml Whole Blood Sodium Heparin Flow Cytometry Next Working Day","",0],
  ["HM033","CD4 By Flowcytometry","ALC, CD4 (Helper T cells), Absolute CD4",1800,"Whole Blood EDTA","Flow Cytometry",48],
  ["MD006","CEBPA Mutation Detection","",7800,"Whole Blood EDTA","PCR",264],
  ["MD177","CEL/HES Prognostic Gene Panel","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["CG010","CEP 12, Trisomy 12 By FISH","",5300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG011","CEP 8, Trisomy 8 By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["BC113","Chromogranin A","",7500,"Plasma EDTA","ELISA",72],
  ["HM034","Chronic Lymphocytic Leukemia (CLL) Diagnostic Panel By Flowcytometry","",16200,"Whole Blood EDTA & 3ml Whole Blood Sodium Heparin / Bone Marrow Sodium Heparin","Flow Cytometry",48],
  ["HM113","Chronic Lymphocytic Leukemia (CLL) MRD Panel By Flowcytometry","",12500,"Whole Blood EDTA / 5ml Whole Blood Sodium Heparin / Bone Marrow","Flow Cytometry",96],
  ["CG012","Chronic Lymphocytic Leukemia (CLL) Panel By FISH","ATM gene (11q), 17p del, 13q14, & +12 (trisomy 12)",9300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",192],
  ["MD475","Chronic Lymphoid Leukemia Panel By NGS","Del 17p, Trisomy 11, Trisomy 12, del 13q",8000,"Whole Blood EDTA / Bone Marrow","Next Generation Sequencing",144],
  ["CG071","Chronic Myeloid Leukemia (CML) Panel By FISH","BCR-ABL Translocation, iso 17q, Deletion 7, Trisomy 8",7500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["MD179","Chronic Myeloproliferative Disorder Gene Panel (CMPD)","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD182","CLL Prognostication/Risk Stratification Gene Panel","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["CG013","cMYC Breakapart By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["MD011","Colorectal Cancer Panel KRAS, NRAS, BRAF","",14600,"Paraffin Embedded Tissue Blocks / FFPE","Sanger Sequencing",192],
  ["MD474","Colorectal Cancer- Theranostic Panel (Hot Spot) KRAS, NRAS, HRAS, BRAF, PIK3CA, AKT1, PTEN, SMAD4","",24000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",504],
  ["MD186","Comprehensive Leukemia Gene Panel","",24000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD481","ctDNA for EGFR HOTSPOT mutations in EGFR (Exons 18, 19, 20, 21; includes T790M)","",15500,"Whole Blood EDTA","Next Generation Sequencing",168],
  ["MD482","ctDNA for EGFR T790M & C797S HOTSPOT mutations in EGFR (T790M - indicating resistance to first & second gen TKI and C797S indicating resistance to third gen TKIs)","",13500,"Whole Blood EDTA","Next Generation Sequencing",288],
  ["MD483","ctDNA for Hot Spot Mutations in 4 Genes (EGFR, KRAS, NRAS, BRAF) HOTSPOT mutations in EGFR (Exons 18, 19, 20, 21; includes T790M), KRAS (Exons 2, 3, 4),NRAS (Exons 2, 3, 4),BRAF (V600E)","",24000,"Whole Blood EDTA","Next Generation Sequencing",288],
  ["BC130","CYFRA 21-1 (Lung Cancer Marker)","",2900,"SST Yellow top Electro","chemiluminescence",48],
  ["CY001","Cytology For Malignant Cells","",400,"Body Fluids / Urine / Sputum Cytocentrifuge Next Working Day","",0],
  ["CG014","Deletion 13Q By FISH","",4700,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG038","Deletion 20Q By FISH","",5700,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG015","Deletion 5Q By FISH","",5700,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG016","Deletion 7Q By FISH","",4300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG017","Deletion/Monosomy 5 By FISH","",5700,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["CG018","Deletion/Monosomy 7 By FISH","",4300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["CG019","DiGeorge Syndrome By FISH","",6000,"Whole Blood Sodium Heparin","FISH",168],
  ["MD503","DPYD IVS14+1G>A Mutation Analysis","",6000,"Whole Blood EDTA","Sanger Sequencing",168],
  ["CG020","E2A (TCF3) Breakapart By FISH","",4300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["MD479","EGFR (T790M, L858R, Exon 19 deletion) Screening by ddPCR","",13500,"Paraffin Embedded Tissue Blocks / 4ml Whole Blood EDTA Droplet Digital PCR 5 Working Days CG09 EGFR Gene Amplification By FISH R2 9300 Paraffin Embedded Tissue Blocks / FFPE","FISH",120],
  ["MD020","EGFR Mutation Detection By RTPCR","Exon 18, 19, 20, 21",7600,"Paraffin Embedded Tissue Blocks / FFPE","Real Time PCR",120],
  ["MD480","EGFR T790M Mutation Screening by ddPCR","",8500,"Paraffin Embedded Tissue Blocks / Whole Blood EDTA Droplet Digital PCR 5 Working Days CG10 EML4 ALK Translocation By FISH R2 9600 Paraffin Embedded Tissue Blocks / FFPE","FISH",216],
  ["CG075","ETV6-RUNX1 t(12;21) (p13;q22) By FISH","",4200,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["CG021","Ewing Sarcoma By FISH","",7000,"Paraffin Embedded Tissue Blocks / FFPE","FISH",216],
  ["CG022","Fanconi Anemia (FA) Stress Cytogenetics","",8000,"Whole Blood Sodium Heparin Cell Culture","",192],
  ["CG058","FGFR1 (8p12) Gene Rearranfement By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["HP140","Final Diagnosis Panel By IHC","",8600,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Microscopy,","IHC",192],
  ["CY002","Fine Needle Aspiration Cytology (FNAC)","",700,"Aspirate Material From Breast / Superficial Lumps / CT Or USG Guided Deep Lumps. 4 Slides & Fix Immediately In Absolute Alcohol For 30 Minutes. Staining & Microscopy Next Working Day","",0],
  ["MD023","FIP1L1-PDGFRA Gene Rearrangement By PCR","",7000,"Whole Blood EDTA / Bone Marrow","PCR",264],
  ["MD486","FLT3 D835 Point Mutation Analysis","",4600,"Whole Blood EDTA / Bone Marrow","Sanger Sequencing",168],
  ["MD024","FLT3 Mutation Detection, Qualitative This assay is useful for the qualitative detection of FLT3-ITD mutations associated with Acute Myeloid Leukemia","",3500,"Whole Blood EDTA / Bone Marrow","PCR",72],
  ["MD326","Gastrointestinal Stromal Tumor (GIST) Panel: Cancer Targeted Gene Panel CD117, DOG-1, ERBB2, KIT, BRAF, PDGFRA, TP53","",24000,"Paraffin Embedded Tissue Blocks / FFPE IHC,","NGS",288],
  ["CG025","HER2/neu By FISH","",11900,"Paraffin Embedded Tissue Blocks / FFPE","FISH",216],
  ["MD140","Hereditary Breast & Ovarian Cancer Syndrome (HBOC) Extended Panel By NGS","",20500,"Whole Blood EDTA","Next Generation Sequencing",672],
  ["HP001","Histopathology: Large Tissue Biopsy","",1500,"Bilateral Adnexa, Uterus With Cervix (Hysterectomy), Ovarian / Adenexal Mass (<10Cm), Prostate Biopsy, Cyst, Placental Biopsy, Bilateral Tonsil, Breast Lump Biopsy (>5cm), One side thyroid, Total hysterectomy with one side salpingo- oophorectomy, Total hysterectomy with bilateral salpingectomy in 10% Formalin Leica Automated Tissue Processor & Stainer","Histopathology",120],
  ["HP002","Histopathology: Medium Tissue Biopsy","",900,"Fibroid, Breast Lump Biopsy (<5cm), Bone Biopsy (Depends On Size, Bill As Large If Needed), Urinary Bladder, Vas Deferens, Polyps, Lipoma, Upper GI Biopsy (Esophagus, Antral, Stomach, Duodenum), Lower GI Biopsy (Jejunum, Ileum, Colon, Rectum), Pilonidal Sinus, Bilateral Fallopian Tubes, Hemaroids/Fistula, Product Of Conception (POC), Tonsil, TURP Chips In 10% Formalin Leica Automated Tissue Processor & Stainer","Histopathology",96],
  ["HP148","Histopathology: Radical Tissue Biopsy","",4500,"Modified Radical Mastectomy (MRM) , Radical Tissue in 10% Formalin Leica Automated Tissue Processor & Stainer","Histopathology",192],
  ["HP003","Histopathology: Small Tissue Biopsy","",700,"Oral Cavity Biopsy, Gall Bladder, Appendix, Punch Biopsy, Endometrial Biopsy, Cervical Biopsy, Skin Biopsy, Nasal Polyp, Tongue Biopsy, Upper GI Biopsy (Esophagus, Antral, Stomach, Duodenum), Lower GI Biopsy (Jejunum, Ileum, Colon, Rectum), Vaginal Flap/Polyp, Synovial Biopsy In 10% Formalin Leica Automated Tissue Processor & Stainer","Histopathology",72],
  ["HM052","HLA B27 By Flowcytometry","",2400,"Whole Blood EDTA","Flow Cytometry",48],
  ["BC447","Human Chorionic Gonodotropin (HCG), Tumor Marker","",660,"SST Yellow top","Chemiluminescence (CLIA",4],
  ["BC179","Human Epididymis Protein 4 (HE4)","",2300,"SST Yellow top ECLIA Same Day","",0],
  ["CG068","iAMP21 By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["MD045","IDH1 & IDH2 Gene Mutations","",8000,"Paraffin Embedded Tissue Blocks / FFPE","Sanger Sequencing",312],
  ["CG026","IGH Gene Rearrangement By FISH","",4800,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG027","IGH/BCL2 t(14;18) Follicular Lymphoma By FISH","",7000,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["CG076","IGH/CCND1 t(11;14) (q13;q32) By FISH","",5500,"Bone Marrow In Sodium Heparin","FISH",144],
  ["CG028","IGH/FGFR3 t(4;14) By FISH","",4300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["CG029","IGH/MAF t(14;16) By FISH","",4300,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["HP055","Immunohistochemistry: 34 Beta E12 (HMW-CK)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP004","Immunohistochemistry: Adrenocorticotropic Hormone (ACTH)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP005","Immunohistochemistry: ALK1","",1800,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP058","Immunohistochemistry: ALKD5F3 For Lung Tumors","",4800,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP057","Immunohistochemistry: Alpha Fetoprotein (AFP)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP093","Immunohistochemistry: Amacr (P504S)","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP011","Immunohistochemistry: Androgen Receptor (AR)","",2700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP061","Immunohistochemistry: Any 3 Markers","",5400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP063","Immunohistochemistry: Any 5 Markers","",6300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP007","Immunohistochemistry: BCL-2 Protein (BCL-2)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP008","Immunohistochemistry: BCL-6","",2100,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP064","Immunohistochemistry: Ber-EP4","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP065","Immunohistochemistry: BOB1","",2400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP156","Immunohistochemistry: BRAF V600E","",2700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP010","Immunohistochemistry: Breast Cancer Panel ER, PR, HER2Neu","",5400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (IHC) 4 Working Days HP010A Immunohistochemistry: Breast CancerQuad ER, PR, Her2neu, Ki-67 R2 6270 Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP012","Immunohistochemistry: CA 125","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP013","Immunohistochemistry: CA 19.9","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP014","Immunohistochemistry: Calcitonin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP015","Immunohistochemistry: Calponin","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP016","Immunohistochemistry: Calretinin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP017","Immunohistochemistry: Carcinoembryonic Antigen (CEA)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP018","Immunohistochemistry: Cathepsin-D","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP019","Immunohistochemistry: CD10","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP020","Immunohistochemistry: CD117 / C-Kit","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP021","Immunohistochemistry: CD138","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP083","Immunohistochemistry: CD15","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP022","Immunohistochemistry: CD1A","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP066","Immunohistochemistry: CD2","",2400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP023","Immunohistochemistry: CD20 (Pan B Cell Antigen)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP024","Immunohistochemistry: CD21","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP025","Immunohistochemistry: CD23","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP026","Immunohistochemistry: CD3 (Pan T Cell)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP027","Immunohistochemistry: CD30 (Ki-1 Antigen)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP067","Immunohistochemistry: CD31","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP028","Immunohistochemistry: CD34","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP029","Immunohistochemistry: CD4 (T Helper Cell)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP068","Immunohistochemistry: CD43","",2400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP030","Immunohistochemistry: CD45/ Leucocyte Common Antigen (LCA)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP069","Immunohistochemistry: CD5","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP070","Immunohistochemistry: CD56","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP071","Immunohistochemistry: CD57","",2400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP072","Immunohistochemistry: CD61","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP073","Immunohistochemistry: CD68","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP074","Immunohistochemistry: CD7","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP075","Immunohistochemistry: CD79A","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP031","Immunohistochemistry: CD8","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP076","Immunohistochemistry: CD99 (MIC-2)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP032","Immunohistochemistry: CDX-2","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP050","Immunohistochemistry: c-erbB-2 (HER-2/neu)","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP033","Immunohistochemistry: Chromogranin A","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP157","Immunohistochemistry: c-MET","",6500,"Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP034","Immunohistochemistry: Cyclin-D1","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP035","Immunohistochemistry: Cytokeratin 19","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP136","Immunohistochemistry: Cytokeratin 20","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP036","Immunohistochemistry: Cytokeratin 5/6","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP037","Immunohistochemistry: Cytokeratin 7","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP056","Immunohistochemistry: Cytokeratin AE1 / AE3","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP038","Immunohistochemistry: Desmin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP006","Immunohistochemistry: DOG-1","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP039","Immunohistochemistry: E-Cadherin (ECAD)","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP040","Immunohistochemistry: Epidermal Growth Factor Receptor (EGFR)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP041","Immunohistochemistry: Epithelial Membrane Antigen (EMA)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP077","Immunohistochemistry: Epstein Barr Virus (EBV)","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP043","Immunohistochemistry: Estrogen Receptor (ER)","",1600,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP042","Immunohistochemistry: Estrogen Receptor (ER) & Progesterone Receptor (PR) ER & PR","",2690,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP044","Immunohistochemistry: Factor VIII","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP045","Immunohistochemistry: Follicle Stimulating Hormone (FSH)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP078","Immunohistochemistry: GCDFP-15","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP046","Immunohistochemistry: Glial Fibrillary Acidic Protein (GFAP)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP047","Immunohistochemistry: Growth Hormone (GH)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP079","Immunohistochemistry: H-Caldesmon","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP080","Immunohistochemistry: HepPar-1","",2400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP158","Immunohistochemistry: Her 2 Gastric Tissue","",4000,"Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP054","Immunohistochemistry: HMB-45","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP009","Immunohistochemistry: Human Chorionic Gonadotropin (Beta HCG)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP150","Immunohistochemistry: Human Herpesvirus-8 (HHV-8)","",2800,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP098","Immunohistochemistry: Inhibin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP082","Immunohistochemistry: Isocitrate Dehydrogenase (IDH-1)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP099","Immunohistochemistry: Kappa Light Chain","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP100","Immunohistochemistry: Ki-67 (Proliferating Cells)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP101","Immunohistochemistry: Lamda Light Chain","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP159","Immunohistochemistry: Lung Tumor Panel ALK D5F3, ROS1, c-MET","",11000,"Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP085","Immunohistochemistry: Luteinizing Hormone (LH)","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP102","Immunohistochemistry: Melan-A","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP048","Immunohistochemistry: Microsatellite Instability (MSI) Panel MLH-1, MSH-2, MSH-6, PMS-2","",9300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP089","Immunohistochemistry: MUM1","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP103","Immunohistochemistry: Myeloperoxidase (MPO)","",2000,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP090","Immunohistochemistry: Myogenin","",2400,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP084","Immunohistochemistry: Myoglobin","",2700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP091","Immunohistochemistry: Napsin A","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP104","Immunohistochemistry: Neuron Specific Enolase (NSE)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP092","Immunohistochemistry: OCT-2","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP105","Immunohistochemistry: P16","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP152","Immunohistochemistry: p40","",1700,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP106","Immunohistochemistry: p53 (Mutant Wild Type)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP107","Immunohistochemistry: p63","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP108","Immunohistochemistry: PAN Cytokeratin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP109","Immunohistochemistry: PAX-5","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP117","Immunohistochemistry: PAX-8","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP110","Immunohistochemistry: PD-L1 Clone SP263","",3600,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP111","Immunohistochemistry: Placental Alkaline Phosphatase (PLAP)","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP112","Immunohistochemistry: Progesterone Receptor (PR)","",1600,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP113","Immunohistochemistry: Prolactin (PRL)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP114","Immunohistochemistry: Prostate Specific Antigen (PSA)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP096","Immunohistochemistry: pS2","",1800,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP049","Immunohistochemistry: ROS1","",4500,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP116","Immunohistochemistry: S-100 Protein","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP118","Immunohistochemistry: Smooth Muscle Actin (SMA)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP119","Immunohistochemistry: Synaptophysin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP120","Immunohistochemistry: Terminal Deoxynucleotidyl Transferase (TDT)","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP121","Immunohistochemistry: Thyroglobulin (TG)","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP081","Immunohistochemistry: Thyroid Stimulating Hormone (TSH)","",2200,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP122","Immunohistochemistry: Thyroid Transcription Factor (TTF-1)","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",144],
  ["HP123","Immunohistochemistry: Vimentin","",1900,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["HP097","Immunohistochemistry: WT-1","",2300,"Tissue In 10% Formalin / Paraffin Embedded Tissue Blocks Immunohistochemistry (","IHC",96],
  ["MD047","Inv(16) By PCR","",4500,"Whole Blood EDTA / Bone Marrow","PCR",192],
  ["CG059","Inv(16) t(16;16) (p13.1;q22) By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["CG066","Inv(3) (MECOM, 3q26) Gene Rearrangement By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["CG072","Iso 17q By FISH","",4200,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["CG065","JAK2 (9p24) Gene Rearrangement By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["MD048","JAK2 Exon 12 Mutation","",5800,"Whole Blood EDTA / Bone Marrow","Real Time PCR",264],
  ["MD471","JAK2 Exon 14 Mutation","",5700,"Whole Blood EDTA / Bone Marrow","Real Time PCR",120],
  ["MD484","JAK2 Gene Analysis, 2 Exons (12 & 14)","",8500,"Whole Blood EDTA / Bone Marrow","Sanger Sequencing",168],
  ["MD050","JAK2 V617 Reflex Panel JAK2 V617 Reflex to JAK 2 Exon 12 Mutation","",8000,"Whole Blood EDTA Real Time PCR,","Fragment Analysis",192],
  ["MD049","JAK2 V617F Mutation Detection","",5700,"Whole Blood EDTA / Bone Marrow","Real Time PCR",120],
  ["MD239","Juvenile Myelomonocytic Leukemia (JMML) Risk Stratification Gene Panel","",20500,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["CG052","Karyotyping: Hematologic Malignancy","",3800,"Whole Blood Sodium Heparin / Bone Marrow Cell Culture","",144],
  ["MD490","KIT Gene Analysis, 2 Exons (9, 11)","",14000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",168],
  ["MD491","KIT Gene Analysis, 4 Exons (9, 11, 13, 17)","",12000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",240],
  ["MD054","KRAS Mutation Detection","",8100,"Paraffin Embedded Tissue Blocks / FFPE PCR & Sequencing 8 Working Days PL42 LBC With HPV DNA Detector R4 1500 Cervical Brushings in LBC Microscopy, PCR Sequencing Wed, Fri, Mon","",0],
  ["MD493","Leukemia Panel By RT PCR","del1(p32), t(1;11)(MLL-EPS15), t(1;11)(MLL-MLLT11), t(1;19), t(3;5), t(3;21), t(4;11), t(5;12), t(5;17), t(6;9), t(6;11), t(8;21), t(9;9), t(9;11), t(9;12), t(9,22), t(10;11), t(11;17) (MLL-MLLT6), t(11;17)(ZBTB16-RARA), t(11;19)(MLL-ELL), t(11;19)(MLL-MLLT1), t(12;21), t(12;22), t(15;17), inv(16), t(16;21), t(17;19), t(X;11)",8000,"Whole Blood EDTA / Bone Marrow","RT PCR",120],
  ["CY005","Liquid Based Cytology (LBC)","",1300,"Cervical Brushings in LBC","Microscopy",48],
  ["MD478","Liquid Biopsy For 56 Theranostic Genes ABL1, AKT1, ALK, APC, ATM, BRAF (inclusive of v600E), CDH1, CDKN2A, CSF1R, CTNNB1, DDR2, DNMT3A, EGFR, ERBB2, ERBB4, EZH2, FBXW7, FGFR1, FGFR2, FGFR3, FLT3, FOXL2, GNA11, GNAQ, GNAS, HNF1A, HRAS, IDH1, IDH2, JAK2, JAK3, KDR, KIT, KRAS, MAP2K1/MEK1, MET, MLH1, MPL, MSH6, NOTCH1, NPM1, NRAS, PDGFRA, PIK3CA, PTEN, PTPN11, RB1, RET, SMAD4, SMARCB1, SMO, SRC, STK11, TP53, TSC1, VHL","",24000,"Whole Blood EDTA","Next Generation Sequencing",504],
  ["MD473","Liquid Biopsy Fusion Gene Panel","",20000,"Whole Blood EDTA","Next Generation Sequencing",504],
  ["CG077","Lung Cancer (ALK & ROS1) Gene Rearrangement By FISH","ALK, ROS1",13000,"Paraffin Embedded Tissue Blocks","FISH",144],
  ["PL216","Lung Cancer Combo Panel ALK D5F3, ROS1 By IHC, BRAF V600E, EGFR By RT PCR","",11000,"Paraffin Embedded Tissue Blocks IHC,","RT PCR",168],
  ["MD056","Lung Cancer Mutation Panel- 1 EGFR By Sequencing, ALK1 By IHC","",12000,"Paraffin Embedded Tissue Blocks / FFPE Sanger Sequencing,","IHC",192],
  ["MD058","Lung Cancer Mutation Panel- 3 EGFR by Sequencing, ALK by IHC, ROS1 by FISH","",21500,"Paraffin Embedded Tissue Blocks / FFPE Sanger Sequencing, IHC,","FISH",192],
  ["MD251","MDS Prognostication And Risk Stratification Gene Panel","",20500,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD060","Microsatellite Instability (MSI) By PCR","",10800,"Paraffin Embedded Tissue Blocks / FFPE","PCR",192],
  ["HM047","Minimal Residual Disease (MRD) For B- ALL By Flowcytometry","",11200,"Bone Marrow Sodium Heparin","Flow Cytometry",48],
  ["HM048","Minimal Residual Disease (MRD) For T- ALL By Flowcytometry","",14600,"Bone Marrow Sodium Heparin & 3ml Whole Blood Sodium Heparin","Flow Cytometry",96],
  ["CG032","MLL By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",168],
  ["MD311","MLPA- BRCA1 & BRCA2 Deletion/Duplication","",14300,"Whole Blood EDTA","MLPA",720],
  ["MD501","MLPA- IKZF1 & CDKN2A Deletion/Duplication Analysis","",8000,"Whole Blood EDTA","MLPA",336],
  ["MD492","MLPA- Lynch syndrome (HNPCC) Deletion/Duplication Analysis MLH1, MSH2, EPCAM","",8000,"Whole Blood EDTA","MLPA",336],
  ["MD122","MLPA- Retinoblastoma (RB1) Deletion/Duplication Analysis","",11000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","MLPA",360],
  ["MD499","MLPA- TP53 Gene Deletion/Duplication Analysis","",8000,"Whole Blood EDTA","MLPA",336],
  ["MD500","MLPA- Von Hippel Lindau Syndrome (VHL) Deletion/Duplication Analysis","",8000,"Whole Blood EDTA","MLPA",336],
  ["MD487","MPL-S204P Gene Analysis","",6000,"Whole Blood EDTA / Bone Marrow","Sanger Sequencing",240],
  ["MD488","MPL-Y591 Gene Analysis","",6000,"Whole Blood EDTA / Bone Marrow","Sanger Sequencing",240],
  ["MD259","MPN Prognostication & Risk Stratification Panel","",20500,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["CG033","Multiple Myeloma By FISH","",11000,"Whole Blood Sodium Heparin / Bone Marrow","FISH",192],
  ["HM058","Multiple Myeloma MRD Panel By Flowcytometry","CD45, CD19, CD20, CD27, CD38, CD138, CD56, CD117, CD200, CD81, Kappa, Lambda",13000,"Bone Marrow Sodium Heparin & 2 Smears Flow Cytometry 4 Working Days PL04 Multiple Myeloma Panel Quantitaive, Serum Protein Electrophoresis, Immunofixation, IgG, IgM, IgA, Free Light Chains - Kappa & Lambda, Beta 2 Microglobulin R2 8600 3ml SST Yellow top CLIA, Nephelometry,","Electrophoresis",144],
  ["MD494","MYD88 Gene L265P Mutation Analysis","",6000,"Paraffin Embedded Tissue Blocks / 4 ml Whole Blood EDTA","Sanger Sequencing",240],
  ["HM115","Myelodysplasia Panel By Flowcytometry","",10500,"Whole Blood EDTA / 3ml Whole Blood Sodium Heparin / Bone Marrow Sodium Heparin","Flow Cytometry",96],
  ["HM114","Myelodysplastic Syndrome (MDS) MRD Panel By Flowcytometry","",12500,"Bone Marrow In Sodium Heparin","Flow Cytometry",96],
  ["CG034","Myelodysplastic Syndrome (MDS) Panel By FISH","FISH for trisomy 8 + del7q + del5q + del20q + Monosomy 7 + Monosomy 5",8900,"Whole Blood Sodium Heparin / Bone Marrow","FISH",192],
  ["HM111","Myelodysplastic Syndrome (MDS) Panel By Flowcytometry","",11000,"Whole Blood EDTA / Bone Marrow","Flow Cytometry",96],
  ["MD061","Myeloproliferative Leukemia (MPL) Mutation Detection","",4900,"Whole Blood EDTA / Bone Marrow PCR Sequencing","",216],
  ["CG082","Myeloproliferative Neoplasm (MPN) Panel By FISH","PDGFRA, PDGFRB, FGFR1, JAK2",7600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["MD062","Myeloproliferative Neoplasm (MPN) Panel By PCR","JAK2 V617F, CALR & MPL MUTATION",12400,"Whole Blood EDTA Real Time PCR, Sequencing,","Fragment Analysis",264],
  ["MD472","Non Small Cell Lung Cancer (NSCLC) NGS Panel (Hot Spot) ALK, BRAF, EGFR, ERBB2, MET, PIK3CA, RET, KRAS, NRAS, PTEN, AKT1, DDR2, HRAS, MAP2K1","",19000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",504],
  ["MD067","NPM1 Mutation Detection","",4300,"Whole Blood EDTA / Bone marrow PCR Sequencing /","Fragment Analysis",144],
  ["MD069","O6-Methylguanine Methyltransferase (MGMT) Promoter","",9100,"Paraffin Embedded Tissue Blocks / FFPE","PCR",408],
  ["MD322","Oncocliffe Comprehensive Cancer Panel","",50000,"Whole Blood EDTA / Isolated Genomic DNA","Next Generation Sequencing",1080],
  ["CG062","PDGFR Alpha (4q12) Gene Rearrangement By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["CG061","PDGFR Beta (5q33) Gene Rearrangement By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["MD495","PDGFRA Gene Analysis, 3 Exons (12, 14, 18)","",10000,"Paraffin Embedded Tissue Blocks / 4ml Whole Blood EDTA / Bone Marrow","Sanger Sequencing",240],
  ["MD151","Philadelphia Chromosome (BCR/ABL Qualitative)","",3300,"Whole Blood EDTA / Bone Marrow EDTA","PCR",72],
  ["MD073","Philadelphia Chromosome (BCR/ABL Quantitative)","",6500,"Whole Blood EDTA","PCR",120],
  ["CG060","PML Ra Ra t(15;17) By FISH","",4600,"Whole Blood Sodium Heparin / Bone Marrow","FISH",120],
  ["MD074","PML Ra Ra t(15;17), Qualitative","",5600,"Whole Blood EDTA / Bone Marrow","Real Time PCR",120],
  ["MD075","PML Ra Ra t(15;17), Quantitative","",5600,"Whole Blood EDTA / Bone Marrow","Real Time PCR",120],
  ["BC418","Progastrin Releasing Peptide (ProGRP)","",8900,"EDTA Plasma CMIA","",48],
  ["MD496","PTEN Gene Analysis","",20500,"Whole Blood EDTA","Sanger Sequencing",504],
  ["MD476","RAS Extended Profiling Analysis by NGS","HOTSPOT Mutations in: Exon 2, 3 & 4 of KRAS gene ; Exon 2, 3 & 4 of NRAS gene ; Exon 15 of BRAF gene For theranostic monitoring of colorectal cancers",16000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",288],
  ["MD497","RET Oncogene- 2 Exons Exons- 10, 11","",8500,"Whole Blood EDTA","Sanger Sequencing",240],
  ["MD498","RET Oncogene- 8 Exons Exons- 5, 8, 10, 11, 13, 14, 15, 16","",18000,"Whole Blood EDTA","Sanger Sequencing",504],
  ["CG069","Retinoblastoma Gene 13q14 Region By FISH","",5000,"Bone Marrow In Sodium Heparin","FISH",72],
  ["BC250","ROMA (Ovarian Malignancy Risk Algorithm) HE4, CA 125, ROMA Value","",3200,"SST Yello Top Serum ECLIA Same Day","",0],
  ["CG063","ROS1 (6q22) Rearrangment By FISH","",7000,"Paraffin Embedded Tissue Blocks","FISH",120],
  ["CG070","RUNX-RUNX1 t(8;21) (q22;q22) By FISH","",4500,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["MD485","SF3B1 Mutation Analysis","",6000,"Whole Blood EDTA / Bone Marrow","Sanger Sequencing",168],
  ["MD468","Somatic 161 Gene Panel","",39000,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",480],
  ["MD477","Somatic Cancer Mutation Panel (Hot Spot Tumor Panel) ABL1, AKT1, ALK, APC, ATM, BRAF (inclusive of v600E), CDH1, CDKN2A, CSF1R, CTNNB1, DDR2, DNMT3A, EGFR, ERBB2, ERBB4, EZH2, FBXW7, FGFR1, FGFR2, FGFR3, FLT3, FOXL2, GNA11, GNAQ, GNAS, HNF1A, HRAS, IDH1, IDH2, JAK2, JAK3, KDR, KIT, KRAS, MAP2K1/MEK1, MET, MLH1, MPL, MSH6, NOTCH1, NPM1, NRAS, PDGFRA, PIK3CA, PTEN, PTPN11, RB1, RET, SMAD4, SMARCB1, SMO, SRC, STK11, TP53, TSC1, VHL","",22500,"Paraffin Embedded Tissue Blocks","Next Generation Sequencing",504],
  ["CG067","TCRA/D (14q11.2) Gene Rearrangement By FISH","",4200,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["BC260","Testicular Cancer Monitor AFP & Beta HCG Cancer Markers","",1000,"SST Yellow Top Serum Chemiluminescence (CLIA) Same Day","",0],
  ["CG074","Trisomy 11 By FISH","",4200,"Whole Blood Sodium Heparin / Bone Marrow","FISH",144],
  ["MD091","WT1 Mutation Detection By PCR","",9060,"Whole Blood EDTA & Bone Marrow","PCR",264],
  ["HP155","Bone Marrow Biopsy","",1400,"Bone Marrow Biopsy In 10% Formalin / Paraffin Embedded Tissue Blocks Processing, Staining,","Histopathology",168],
  ["HM030","Bone Marrow Slide Review","",750,"Slides / Smears","Microscopy",48],
  ["MD518","BRAF Mutation Analysis by NGS","",14000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["MD321","BRCA1 & BRCA2 Mutation Analysis By NGS","",14000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) /3 ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",336],
  ["MD312","Breast Cancer Gene Panel","",24000,"Whole Blood EDTA","Next Generation Sequencing",1080],
  ["MD470","Chronic Neutrophilic Leukemia (CNL), CSF3R Gene Analysis","",9600,"Whole Blood EDTA / Bone Marrow","Sanger Sequencing",264],
  ["MD010","C-KIT Mutation by PCR","",5800,"Whole Blood EDTA","PCR",168],
  ["MD523","ERBB2 Mutation Analysis by NGS","(Hotspot Regions) ERBB2, ERBB4",15000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["MD156","FGFRs Mutation Analysis by NGS","FGFR1, FGFR2, FGFR3",21400,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["MD529","Glioma Solid Tumor Gene Panel by NGS","Hotspot;SNVs,smallINDELs,CNVs: BRAF, CDKN2A, EGFR, HRAS, IDH1, IDH2, KRAS, MET, NRAS, PIK3CA, PTEN, TP53",19000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["HP149","Histopathology: Extra Large Tissue Biopsy","",2500,"Uterus With Cervix With Bilateral Adnexa (Hysterectomy With BSO), Ovarian / Adenexal Mass (>10Cm), Hemicolectomy, Gastrectomy, Nephrectomy, Thyroidectomy In 10% Formalin Leica Automated Tissue Processor & Stainer","Histopathology",168],
  ["HP141","Histopathology: Kidney Biopsy With DIF Histopathology & IFA IgG, IgM, IgA. C3, C1q","",4400,"Submit 2 Kidney Biopsy Specimens:- 1 Specimen In Buffered Normal Saline For Dif Studies & 1 Specimen In 10% Formal Saline. Tissue container available from Redcliffe labs. Fluorescence & Light","Histopathology",168],
  ["HP053","Histopathology: Liver Biopsy","",2000,"Liver Tissue In 10% Formalin Leica Automated Tissue Processor & Stainer","Histopathology",168],
  ["MD520","IDH1 & IDH2 Gene Analysis by NGS","(Hotspot Regions)",14000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["HM116","Leukemia Lymphoma Panel By Flowcytometry","",16200,"Whole Blood EDTA & 5ml Whole Blood Sodium Heparin / Bone Marrow Sodium Heparin Flow Cytometry 2 Working Days MD511B Lung Cancer Advance Panel by NGS ALK, EGFR, BRAF, MET (includes Ex-14 skipping), RET, ERBB2, KRAS, HRAS, RET, ROS1 (SNVs, small INDELs, CNVs); ALK, ROS1, RET and NTRK1 (Fusions) R2 35000 FFPE Tissue Blocks / Purified gDNA & RNA NGS 14 Days MD511A Lung Cancer Basic Panel by NGS ALK, EGFR, BRAF, MET, HRAS, KRAS, RET, ROS1 (SNVs & small Indels) R2 28000 FFPE Tissue Blocks / Purified gDNA & RNA","NGS",336],
  ["CG084","MDM2 (12q15) Gene Amplification by FISH","",7600,"Paraffin Embedded Tissue Blocks / FFPE","FISH",168],
  ["MD527","Metastatic Melanoma Panel by NGS","[(Hotspot, INDELs, CNVs; BRAF, NRAS, KRAS, KIT, MAP2K1, CTNNB1, GNAQ & GNA11, CCND1 & KIT) (Fusions; BRAF, NTRK1, ROS1, ALK, RET)]",35000,"FFPE Tissue Blocks / Purified gDNA & RNA","NGS",336],
  ["MD068","NRAS Mutation Detection","",6700,"Paraffin Embedded Tissue Blocks / FFPE PCR Sequencing","",216],
  ["MD524","NTRK1 Gene Fusion by NGS","NTRK1",15000,"FFPE Tissue Blocks / RNA","NGS",336],
  ["MD525","NTRK1/2/3 Gene Fusions by NGS","NTRK1, NTRK2, NTRK3",17500,"FFPE Tissue Blocks / RNA","NGS",336],
  ["CG081","NTRK1/2/3 Gene Rearrangement by FISH","NTRK1(1q21.3), NTRK2 (9q21.3), NTRK3 (15q25.3)",16200,"Paraffin Embedded Tissue Blocks / FFPE","FISH",168],
  ["MD323","Oncocliffe Hereditary Cancer Gene Panel","",20000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD324","Oncocliffe Lynch Syndrome/HNPCC Gene Panel","",14000,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD521","PDGFRA Gene Analysis by NGS","(Hotspot Regions)",14000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["MD272","PDGFRB Gene Sequencing","",20500,"Amniotic Fluid / Chorionic Villus Sampling (CVS) / 3ml Whole Blood EDTA / Purified Genomic DNA","Next Generation Sequencing",672],
  ["MD519","PIK3CA Mutation Analysis by NGS","",14000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
  ["MD077","RAS Mutation Panel KRAS, NRAS","",11900,"Paraffin Embedded Tissue Blocks / FFPE Sanger Sequencing 8 Working Days MD512B Solid Tumor Advanced Panel by NGS SNVs, SmallIndels,CNVs & gene fusions ([(Hotspot, INDELs, CNVs; AKT1, ALK, AR, BRAF, CDK4, CTNNB1, DDR2, EGFR, ERBB2, ERBB3, ERBB4, ESR1, FGFR2, FGFR3, GNA11, GNAQ, HRAS, IDH1, IDH2, JAK1, JAK2, JAK3, KIT, KRAS, MAP2K1, MAP2K2, MET, MTOR, NRAS, PDGFRA, PIK3CA, RAF1, RET, ROS1, SMO, CCND1, CDK6, FGFR1, FGFR4, RAS, MYC, MYCN), Fusions; ABL1, AKT3, ALK, BRAF, EGFR, ERBB2, ETV1, ETV4, FGFR1/2/3, MET, NTRK1/2/3, PPARG, RAF, RET, ROS1) R2 24500 FFPE Tissue Blocks / Purified gDNA & RNA NGS 14 Days MD512A Solid Tumor Basic Panel by NGS AKT1, ALK, AR, BRAF, CDK4, CTNNB1, DDR2, EGFR, ERBB2, ERBB3, ERBB4, ESR1, FGFR2, FGFR3, GNA11, GNAQ, HRAS, IDH1, IDH2, JAK1, JAK2, JAK3, KIT, KRAS, MAP2K1, MAP2K2, MET, MTOR, NRAS, PDGFRA, PIK3CA, RAF1, RET, ROS1, SMO R2 20500 FFPE Tissue Blocks / Purified gDNA & RNA","NGS",336],
  ["MD526","Tissue Specific Breast Triple Negative Test by NGS","EGFR, ERBB2, PIK3CA, PTEN, SMAD4",18000,"FFPE Tissue Blocks / Purified gDNA","NGS",336],
];
