import "dotenv/config";
import { Pool } from "pg";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import { GENETIC_PRODUCTS } from "./genetic-tests-seed-data";

const pool = new Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const labs = [
  {
    slug: "jammu-genetics-hub",
    name: "Jammu Genetics Hub",
    shortName: "JGH",
    isOwn: true,
    logoInitials: "JGH",
    colorHex: "#0b6e5c",
    rating: 4.8,
    ratingCount: 3120,
    // We don't run our own testing lab — this price/booking is ours, but the
    // sample is processed at an accredited partner lab. Never say "NABL
    // Accredited" here; that accreditation belongs to the partner labs.
    accreditation: "We collect, partner labs test",
    turnaroundNote: "Reports in 12–24 hrs",
    homeCollection: true,
  },
  {
    slug: "thyrocare",
    name: "Thyrocare",
    shortName: "Thyrocare",
    isOwn: false,
    logoInitials: "TC",
    colorHex: "#7a4fa3",
    rating: 4.4,
    ratingCount: 218000,
    accreditation: "NABL & CAP Accredited",
    turnaroundNote: "Reports in 24 hrs",
    homeCollection: true,
  },
  {
    slug: "redcliffe-labs",
    name: "Redcliffe Labs",
    shortName: "Redcliffe",
    isOwn: false,
    logoInitials: "RL",
    colorHex: "#1e5f8c",
    rating: 4.5,
    ratingCount: 156000,
    accreditation: "NABL Accredited",
    turnaroundNote: "Reports in 14 hrs",
    homeCollection: true,
  },
  {
    slug: "dr-lal-pathlabs",
    name: "Dr Lal PathLabs",
    shortName: "Dr Lal",
    isOwn: false,
    logoInitials: "LPL",
    colorHex: "#c1502e",
    rating: 4.6,
    ratingCount: 312000,
    accreditation: "NABL & CAP Accredited",
    turnaroundNote: "Reports in 24–48 hrs",
    homeCollection: true,
  },
  {
    slug: "metropolis",
    name: "Metropolis Healthcare",
    shortName: "Metropolis",
    isOwn: false,
    logoInitials: "MH",
    colorHex: "#b6314a",
    rating: 4.3,
    ratingCount: 98000,
    accreditation: "NABL Accredited",
    turnaroundNote: "Reports in 24 hrs",
    homeCollection: true,
  },
  // Specialty genetic-testing partner labs — samples are routed to whichever
  // of these actually offers a given test (real per-lab pricing, sparse —
  // not every partner does every test); much longer turnaround than routine
  // blood work is normal for these. See prisma/genetic-tests-seed-data.ts
  // for what's actually priced where.
  {
    slug: "ampath",
    name: "AMPATH",
    shortName: "AMPATH",
    isOwn: false,
    logoInitials: "AM",
    colorHex: "#2f8f6f",
    rating: 4.4,
    ratingCount: 45000,
    accreditation: "NABL Accredited",
    turnaroundNote: "Reports in 5–7 days",
    homeCollection: true,
    isSpecialtyPartner: true,
  },
  {
    slug: "tata-1mg",
    name: "Tata 1mg",
    shortName: "Tata 1mg",
    isOwn: false,
    logoInitials: "1mg",
    colorHex: "#d4342c",
    rating: 4.5,
    ratingCount: 89000,
    accreditation: "NABL Accredited",
    turnaroundNote: "Reports in 5–10 days",
    homeCollection: true,
    isSpecialtyPartner: true,
  },
  {
    slug: "medgenome",
    name: "MedGenome",
    shortName: "MedGenome",
    isOwn: false,
    logoInitials: "MG",
    colorHex: "#6a3fb5",
    rating: 4.6,
    ratingCount: 12500,
    accreditation: "NABL & CAP Accredited",
    turnaroundNote: "Reports in 7–14 days",
    homeCollection: true,
    isSpecialtyPartner: true,
  },
  {
    slug: "yoda-diagnostics",
    name: "Yoda Diagnostics",
    shortName: "Yoda",
    isOwn: false,
    logoInitials: "YD",
    colorHex: "#b8860b",
    rating: 4.2,
    ratingCount: 3200,
    accreditation: "NABL Accredited",
    turnaroundNote: "Reports in 7–12 days",
    homeCollection: true,
    isSpecialtyPartner: true,
  },
  {
    slug: "lilac-insights",
    name: "Lilac Insights",
    shortName: "Lilac Insights",
    isOwn: false,
    logoInitials: "LI",
    colorHex: "#3c9dbf",
    rating: 4.4,
    ratingCount: 5100,
    accreditation: "NABL Accredited",
    turnaroundNote: "Reports in 7–21 days",
    homeCollection: true,
    isSpecialtyPartner: true,
  },
];

const categories = [
  { slug: "full-body", name: "Full Body Checkup", icon: "ScanHeart", order: 1 },
  { slug: "diabetes", name: "Diabetes", icon: "Droplet", order: 2 },
  { slug: "heart", name: "Heart", icon: "HeartPulse", order: 3 },
  { slug: "thyroid", name: "Thyroid", icon: "Activity", order: 4 },
  { slug: "vitamin", name: "Vitamins", icon: "Sun", order: 5 },
  { slug: "liver-kidney", name: "Liver & Kidney", icon: "Filter", order: 6 },
  { slug: "fever", name: "Fever & Infection", icon: "Thermometer", order: 7 },
  { slug: "womens-health", name: "Women's Health", icon: "Flower2", order: 8 },
  { slug: "senior-care", name: "Senior Citizen", icon: "Users", order: 9 },
  { slug: "general", name: "General Health", icon: "Stethoscope", order: 10 },
  { slug: "bone-joint", name: "Bone & Joint", icon: "Bone", order: 11 },
  { slug: "cancer-screening", name: "Cancer Screening", icon: "Ribbon", order: 12 },
  { slug: "allergy", name: "Allergy", icon: "Wind", order: 13 },
  { slug: "std-screening", name: "STD/STI Screening", icon: "ShieldAlert", order: 14 },
  { slug: "pregnancy", name: "Pregnancy & Antenatal", icon: "Baby", order: 15 },
  { slug: "executive", name: "Executive Checkup", icon: "Briefcase", order: 16 },
  { slug: "child-care", name: "Child Care", icon: "Backpack", order: 17 },
  { slug: "genetic-testing", name: "Genetic Testing", icon: "Dna", order: 18 },
];

type ProductSeed = {
  slug: string;
  name: string;
  type: "TEST" | "PACKAGE";
  category: string;
  parameters: number;
  sampleType: string;
  fasting: boolean;
  fastingHours?: number;
  reportHours: number;
  gender?: "male" | "female" | "both";
  minAge?: number;
  description: string;
  includes: string[];
  popular?: boolean;
  badge?: string;
  // base price used to derive per-lab pricing
  basePrice: number;
  baseMrp: number;
};

const products: ProductSeed[] = [
  {
    slug: "complete-blood-count",
    name: "Complete Blood Count (CBC)",
    type: "TEST",
    category: "general",
    parameters: 24,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description:
      "Measures red cells, white cells and platelets to screen for anaemia, infection and general blood disorders.",
    includes: ["Haemoglobin", "RBC Count", "WBC Count", "Platelet Count", "Differential Count"],
    popular: true,
    badge: "Most Booked",
    basePrice: 299,
    baseMrp: 700,
  },
  {
    slug: "hba1c",
    name: "HbA1c (Glycosylated Haemoglobin)",
    type: "TEST",
    category: "diabetes",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Shows your average blood sugar level over the last 2–3 months — the gold-standard diabetes test.",
    includes: ["HbA1c %", "Estimated Average Glucose"],
    popular: true,
    basePrice: 449,
    baseMrp: 900,
  },
  {
    slug: "fasting-blood-sugar",
    name: "Fasting Blood Sugar (FBS)",
    type: "TEST",
    category: "diabetes",
    parameters: 1,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 6,
    description: "A basic fasting glucose check to screen for diabetes and pre-diabetes.",
    includes: ["Fasting Glucose"],
    basePrice: 99,
    baseMrp: 250,
  },
  {
    slug: "thyroid-profile-total",
    name: "Thyroid Profile Total (T3, T4, TSH)",
    type: "TEST",
    category: "thyroid",
    parameters: 3,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Checks thyroid hormone levels to screen for hypothyroidism and hyperthyroidism.",
    includes: ["Total T3", "Total T4", "TSH"],
    popular: true,
    basePrice: 349,
    baseMrp: 800,
  },
  {
    slug: "lipid-profile",
    name: "Lipid Profile",
    type: "TEST",
    category: "heart",
    parameters: 10,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 12,
    description: "Measures cholesterol and triglycerides to assess your heart disease risk.",
    includes: ["Total Cholesterol", "HDL", "LDL", "VLDL", "Triglycerides"],
    popular: true,
    basePrice: 399,
    baseMrp: 900,
  },
  {
    slug: "liver-function-test",
    name: "Liver Function Test (LFT)",
    type: "TEST",
    category: "liver-kidney",
    parameters: 12,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Evaluates liver enzymes and proteins to check for liver damage or disease.",
    includes: ["SGOT", "SGPT", "Bilirubin", "Alkaline Phosphatase", "Total Protein"],
    basePrice: 399,
    baseMrp: 850,
  },
  {
    slug: "kidney-function-test",
    name: "Kidney Function Test (KFT)",
    type: "TEST",
    category: "liver-kidney",
    parameters: 10,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Assesses kidney health through creatinine, urea and electrolyte levels.",
    includes: ["Creatinine", "Urea", "Uric Acid", "Sodium", "Potassium"],
    basePrice: 449,
    baseMrp: 950,
  },
  {
    slug: "vitamin-d-total",
    name: "Vitamin D Total (25-OH)",
    type: "TEST",
    category: "vitamin",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Checks Vitamin D levels — deficiency is extremely common and linked to bone and immunity issues.",
    includes: ["25-Hydroxy Vitamin D"],
    popular: true,
    basePrice: 799,
    baseMrp: 1800,
  },
  {
    slug: "vitamin-b12",
    name: "Vitamin B12",
    type: "TEST",
    category: "vitamin",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Checks B12 levels, important for nerve health and red blood cell formation.",
    includes: ["Vitamin B12"],
    basePrice: 599,
    baseMrp: 1300,
  },
  {
    slug: "complete-urine-examination",
    name: "Complete Urine Examination (CUE)",
    type: "TEST",
    category: "general",
    parameters: 15,
    sampleType: "Urine",
    fasting: false,
    reportHours: 8,
    description: "Screens for urinary tract infections, kidney issues and diabetes markers in urine.",
    includes: ["Protein", "Glucose", "Pus Cells", "RBC", "Specific Gravity"],
    basePrice: 149,
    baseMrp: 350,
  },
  {
    slug: "dengue-ns1",
    name: "Dengue NS1 Antigen",
    type: "TEST",
    category: "fever",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 6,
    description: "Detects dengue infection early, from day 1 of fever.",
    includes: ["Dengue NS1 Antigen"],
    basePrice: 499,
    baseMrp: 1100,
  },
  {
    slug: "widal-test",
    name: "Widal Test (Typhoid)",
    type: "TEST",
    category: "fever",
    parameters: 4,
    sampleType: "Blood",
    fasting: false,
    reportHours: 8,
    description: "Screens for typhoid fever caused by Salmonella infection.",
    includes: ["TO", "TH", "AH", "BH"],
    basePrice: 199,
    baseMrp: 450,
  },
  {
    slug: "full-body-essential",
    name: "Full Body Checkup — Essential",
    type: "PACKAGE",
    category: "full-body",
    parameters: 62,
    sampleType: "Blood + Urine",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description:
      "A comprehensive yearly screening covering blood count, sugar, lipids, liver, kidney and thyroid — the essentials, in one panel.",
    includes: [
      "Complete Blood Count",
      "Fasting Blood Sugar",
      "Lipid Profile",
      "Liver Function Test",
      "Kidney Function Test",
      "Thyroid Profile (TSH)",
      "Complete Urine Examination",
    ],
    popular: true,
    badge: "Most Booked",
    basePrice: 899,
    baseMrp: 3500,
  },
  {
    slug: "full-body-advanced",
    name: "Full Body Checkup — Advanced",
    type: "PACKAGE",
    category: "full-body",
    parameters: 94,
    sampleType: "Blood + Urine",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description:
      "Our most complete annual screening — everything in Essential plus Vitamin D, B12, iron studies and HbA1c.",
    includes: [
      "Complete Blood Count",
      "HbA1c",
      "Lipid Profile",
      "Liver Function Test",
      "Kidney Function Test",
      "Thyroid Profile Total",
      "Vitamin D Total",
      "Vitamin B12",
      "Iron Studies",
      "Complete Urine Examination",
    ],
    popular: true,
    badge: "Best Value",
    basePrice: 1499,
    baseMrp: 6500,
  },
  {
    slug: "diabetes-screening",
    name: "Diabetes Screening Package",
    type: "PACKAGE",
    category: "diabetes",
    parameters: 8,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 12,
    description: "Everything you need to screen for and monitor diabetes in one booking.",
    includes: ["Fasting Blood Sugar", "Post-Prandial Blood Sugar", "HbA1c", "Urine Microalbumin"],
    basePrice: 649,
    baseMrp: 1600,
  },
  {
    slug: "heart-health",
    name: "Heart Health Package",
    type: "PACKAGE",
    category: "heart",
    parameters: 15,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description: "A focused panel for cardiac risk — lipid profile, ECG-linked markers and inflammation indicators.",
    includes: ["Lipid Profile", "hs-CRP", "Apolipoprotein A1 & B", "Lipoprotein (a)"],
    basePrice: 1199,
    baseMrp: 2800,
  },
  {
    slug: "womens-wellness",
    name: "Women's Wellness Package",
    type: "PACKAGE",
    category: "womens-health",
    parameters: 48,
    sampleType: "Blood + Urine",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    gender: "female",
    description: "A well-rounded screening for women covering hormones, thyroid, iron, bone health and general wellness.",
    includes: [
      "Complete Blood Count",
      "Thyroid Profile Total",
      "Vitamin D Total",
      "Vitamin B12",
      "Iron Studies",
      "Calcium",
      "HbA1c",
    ],
    badge: "Popular with women",
    basePrice: 1299,
    baseMrp: 4200,
  },
  {
    slug: "thyroid-vitamin-combo",
    name: "Thyroid + Vitamin Combo",
    type: "PACKAGE",
    category: "thyroid",
    parameters: 5,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Thyroid profile bundled with Vitamin D and B12 — the three most commonly deficient markers.",
    includes: ["Thyroid Profile Total", "Vitamin D Total", "Vitamin B12"],
    basePrice: 999,
    baseMrp: 2600,
  },
  {
    slug: "senior-citizen-checkup",
    name: "Senior Citizen Full Body Checkup",
    type: "PACKAGE",
    category: "senior-care",
    parameters: 78,
    sampleType: "Blood + Urine",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    minAge: 60,
    description: "A thorough checkup tailored for those above 60 — covering heart, bone, kidney, liver and diabetes risk.",
    includes: [
      "Complete Blood Count",
      "HbA1c",
      "Lipid Profile",
      "Liver Function Test",
      "Kidney Function Test",
      "Thyroid Profile Total",
      "Vitamin D Total",
      "Vitamin B12",
      "Calcium",
      "PSA (men) / Ca-125 (women)",
    ],
    basePrice: 1699,
    baseMrp: 7200,
  },
  {
    slug: "fever-panel",
    name: "Fever Panel",
    type: "PACKAGE",
    category: "fever",
    parameters: 12,
    sampleType: "Blood",
    fasting: false,
    reportHours: 8,
    description: "Covers the most common causes of fever — dengue, typhoid, malaria and a blood count.",
    includes: ["Dengue NS1", "Widal Test", "Malaria Antigen", "Complete Blood Count", "CRP"],
    basePrice: 899,
    baseMrp: 2200,
  },
  {
    slug: "allergy-basic-panel",
    name: "Allergy Basic Panel",
    type: "PACKAGE",
    category: "allergy",
    parameters: 6,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    description: "Screens for common food and environmental allergy triggers using total IgE and key allergens.",
    includes: ["Total IgE", "Dust Mite", "Pollen", "Milk", "Egg", "Peanut"],
    basePrice: 1499,
    baseMrp: 3600,
  },

  // ── Diabetes (more) ──────────────────────────────────────────────────
  {
    slug: "post-prandial-blood-sugar",
    name: "Post Prandial Blood Sugar (PPBS)",
    type: "TEST",
    category: "diabetes",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 6,
    description: "Measures blood sugar 2 hours after a meal to assess how well your body handles glucose.",
    includes: ["Post-Prandial Glucose"],
    basePrice: 99,
    baseMrp: 250,
  },
  {
    slug: "glucose-tolerance-test",
    name: "Glucose Tolerance Test (GTT)",
    type: "TEST",
    category: "diabetes",
    parameters: 3,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 8,
    reportHours: 12,
    description: "Tracks how your body clears a glucose load over time — used to diagnose diabetes and gestational diabetes.",
    includes: ["Fasting Glucose", "1-Hour Glucose", "2-Hour Glucose"],
    basePrice: 349,
    baseMrp: 800,
  },
  {
    slug: "insulin-fasting",
    name: "Fasting Insulin",
    type: "TEST",
    category: "diabetes",
    parameters: 1,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description: "Measures insulin levels to help assess insulin resistance, often used alongside fasting glucose.",
    includes: ["Fasting Insulin"],
    basePrice: 599,
    baseMrp: 1400,
  },

  // ── Heart (more) ─────────────────────────────────────────────────────
  {
    slug: "ecg-resting",
    name: "ECG (Resting)",
    type: "TEST",
    category: "heart",
    parameters: 1,
    sampleType: "ECG Recording",
    fasting: false,
    reportHours: 2,
    description: "A resting electrocardiogram to check your heart's electrical rhythm — done at home with a portable device.",
    includes: ["12-Lead ECG Trace"],
    basePrice: 299,
    baseMrp: 600,
  },
  {
    slug: "troponin-i",
    name: "Troponin I",
    type: "TEST",
    category: "heart",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 6,
    description: "A cardiac injury marker used to help assess chest pain and possible heart muscle damage.",
    includes: ["Troponin I"],
    basePrice: 899,
    baseMrp: 2000,
  },
  {
    slug: "homocysteine",
    name: "Homocysteine",
    type: "TEST",
    category: "heart",
    parameters: 1,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 8,
    reportHours: 24,
    description: "Elevated homocysteine is linked to higher cardiovascular risk — often checked alongside a lipid profile.",
    includes: ["Homocysteine"],
    basePrice: 999,
    baseMrp: 2200,
  },
  {
    slug: "cardiac-risk-package",
    name: "Cardiac Risk Package",
    type: "PACKAGE",
    category: "heart",
    parameters: 18,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description: "A deeper heart-risk workup beyond a basic lipid profile — for anyone with a family history of heart disease.",
    includes: ["Lipid Profile", "hs-CRP", "Homocysteine", "Apolipoprotein A1 & B", "Lipoprotein (a)", "ECG"],
    basePrice: 1799,
    baseMrp: 4500,
  },

  // ── Thyroid (more) ───────────────────────────────────────────────────
  {
    slug: "tsh-only",
    name: "TSH (Thyroid Stimulating Hormone)",
    type: "TEST",
    category: "thyroid",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "The single most useful first-line thyroid test — a quick check before ordering a full panel.",
    includes: ["TSH"],
    basePrice: 199,
    baseMrp: 450,
  },
  {
    slug: "thyroid-antibodies-panel",
    name: "Thyroid Antibodies Panel (Anti-TPO, Anti-TG)",
    type: "TEST",
    category: "thyroid",
    parameters: 2,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    description: "Checks for autoimmune thyroid conditions like Hashimoto's thyroiditis.",
    includes: ["Anti-TPO", "Anti-Thyroglobulin"],
    basePrice: 899,
    baseMrp: 2200,
  },

  // ── Vitamins (more) ──────────────────────────────────────────────────
  {
    slug: "vitamin-a",
    name: "Vitamin A (Retinol)",
    type: "TEST",
    category: "vitamin",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    description: "Checks Vitamin A levels — important for vision, skin and immune health.",
    includes: ["Vitamin A"],
    basePrice: 699,
    baseMrp: 1600,
  },
  {
    slug: "folic-acid",
    name: "Folic Acid (Folate)",
    type: "TEST",
    category: "vitamin",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Checks folate levels — especially important for women who are pregnant or planning pregnancy.",
    includes: ["Folic Acid"],
    basePrice: 549,
    baseMrp: 1200,
  },
  {
    slug: "vitamin-b-complex-package",
    name: "Vitamin B-Complex Package",
    type: "PACKAGE",
    category: "vitamin",
    parameters: 4,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Checks the B-vitamins most commonly deficient in Indian diets, in one panel.",
    includes: ["Vitamin B1", "Vitamin B6", "Vitamin B12", "Folic Acid"],
    basePrice: 1299,
    baseMrp: 3200,
  },

  // ── Liver & Kidney (more) ────────────────────────────────────────────
  {
    slug: "hepatitis-b-surface-antigen",
    name: "Hepatitis B Surface Antigen (HBsAg)",
    type: "TEST",
    category: "liver-kidney",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Screens for active Hepatitis B infection — commonly required before surgery or during pregnancy.",
    includes: ["HBsAg"],
    basePrice: 349,
    baseMrp: 800,
  },
  {
    slug: "hepatitis-c-antibody",
    name: "Hepatitis C Antibody (Anti-HCV)",
    type: "TEST",
    category: "liver-kidney",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Screens for past or current Hepatitis C infection.",
    includes: ["Anti-HCV"],
    basePrice: 599,
    baseMrp: 1400,
  },
  {
    slug: "urine-microalbumin",
    name: "Urine Microalbumin",
    type: "TEST",
    category: "liver-kidney",
    parameters: 1,
    sampleType: "Urine",
    fasting: false,
    reportHours: 12,
    description: "Detects early kidney damage, especially important for people with diabetes or high blood pressure.",
    includes: ["Microalbumin"],
    basePrice: 449,
    baseMrp: 1000,
  },
  {
    slug: "kidney-stone-risk-panel",
    name: "Kidney Stone Risk Panel",
    type: "PACKAGE",
    category: "liver-kidney",
    parameters: 8,
    sampleType: "Blood + Urine",
    fasting: false,
    reportHours: 24,
    description: "Checks the blood and urine markers most linked to kidney stone formation and recurrence.",
    includes: ["Kidney Function Test", "Calcium", "Uric Acid", "Urine Routine"],
    basePrice: 1199,
    baseMrp: 2800,
  },

  // ── Fever & Infection (more) ─────────────────────────────────────────
  {
    slug: "malaria-antigen",
    name: "Malaria Antigen Test",
    type: "TEST",
    category: "fever",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 4,
    description: "A rapid test to detect malaria parasites in the blood.",
    includes: ["Malaria Antigen (P.f/P.v)"],
    basePrice: 299,
    baseMrp: 700,
  },
  {
    slug: "covid19-rtpcr",
    name: "COVID-19 RT-PCR",
    type: "TEST",
    category: "fever",
    parameters: 1,
    sampleType: "Nasal/Throat Swab",
    fasting: false,
    reportHours: 24,
    description: "The gold-standard test to confirm active COVID-19 infection.",
    includes: ["SARS-CoV-2 RNA"],
    basePrice: 499,
    baseMrp: 1200,
  },
  {
    slug: "chikungunya-igm",
    name: "Chikungunya IgM Antibody",
    type: "TEST",
    category: "fever",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Checks for recent chikungunya infection, a mosquito-borne illness with symptoms similar to dengue.",
    includes: ["Chikungunya IgM"],
    basePrice: 799,
    baseMrp: 1800,
  },
  {
    slug: "crp-quantitative",
    name: "CRP (C-Reactive Protein), Quantitative",
    type: "TEST",
    category: "fever",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "A general marker of inflammation or infection in the body.",
    includes: ["C-Reactive Protein"],
    basePrice: 349,
    baseMrp: 800,
  },

  // ── Women's Health (more) ────────────────────────────────────────────
  {
    slug: "pcos-panel",
    name: "PCOS Panel",
    type: "PACKAGE",
    category: "womens-health",
    parameters: 10,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    gender: "female",
    description: "Checks the hormone markers most relevant to diagnosing and monitoring PCOS.",
    includes: ["LH", "FSH", "Testosterone", "Prolactin", "TSH", "Fasting Insulin"],
    basePrice: 1599,
    baseMrp: 4200,
  },
  {
    slug: "pregnancy-test-beta-hcg",
    name: "Pregnancy Test (Beta hCG, Quantitative)",
    type: "TEST",
    category: "womens-health",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 6,
    gender: "female",
    description: "A blood test that confirms pregnancy earlier and more precisely than a urine test.",
    includes: ["Beta hCG"],
    basePrice: 299,
    baseMrp: 700,
  },
  {
    slug: "amh-ovarian-reserve",
    name: "Anti-Müllerian Hormone (AMH)",
    type: "TEST",
    category: "womens-health",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    gender: "female",
    description: "Assesses ovarian reserve — commonly used in fertility planning and evaluation.",
    includes: ["AMH"],
    basePrice: 1899,
    baseMrp: 4500,
  },
  {
    slug: "pap-smear",
    name: "Pap Smear",
    type: "TEST",
    category: "womens-health",
    parameters: 1,
    sampleType: "Cervical Sample",
    fasting: false,
    reportHours: 72,
    gender: "female",
    minAge: 21,
    description: "Screens for abnormal cervical cells that could develop into cervical cancer if untreated.",
    includes: ["Cervical Cytology"],
    basePrice: 999,
    baseMrp: 2200,
  },

  // ── Senior Citizen (more) ────────────────────────────────────────────
  {
    slug: "senior-cardiac-package",
    name: "Senior Citizen Cardiac Package",
    type: "PACKAGE",
    category: "senior-care",
    parameters: 16,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    minAge: 60,
    description: "A heart-focused checkup for older adults, combining lipid, inflammation and ECG screening.",
    includes: ["Lipid Profile", "hs-CRP", "ECG", "Troponin I", "Kidney Function Test"],
    basePrice: 1999,
    baseMrp: 5200,
  },

  // ── General Health (more) ────────────────────────────────────────────
  {
    slug: "iron-studies",
    name: "Iron Studies",
    type: "TEST",
    category: "general",
    parameters: 4,
    sampleType: "Blood",
    fasting: true,
    fastingHours: 8,
    reportHours: 24,
    description: "Checks iron, ferritin and binding capacity to screen for iron-deficiency anaemia or iron overload.",
    includes: ["Serum Iron", "Ferritin", "TIBC", "Transferrin Saturation"],
    basePrice: 799,
    baseMrp: 1800,
  },
  {
    slug: "electrolytes-panel",
    name: "Electrolytes Panel",
    type: "TEST",
    category: "general",
    parameters: 3,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Checks sodium, potassium and chloride — important for hydration, kidney and heart function.",
    includes: ["Sodium", "Potassium", "Chloride"],
    basePrice: 399,
    baseMrp: 900,
  },
  {
    slug: "esr-test",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    type: "TEST",
    category: "general",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "A general marker of inflammation in the body, often checked alongside a CBC.",
    includes: ["ESR"],
    basePrice: 149,
    baseMrp: 350,
  },

  // ── Bone & Joint ──────────────────────────────────────────────────────
  {
    slug: "calcium-total",
    name: "Calcium, Total",
    type: "TEST",
    category: "bone-joint",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Checks blood calcium levels — important for bone health, muscle and nerve function.",
    includes: ["Total Calcium"],
    basePrice: 349,
    baseMrp: 800,
  },
  {
    slug: "vitamin-d-calcium-combo",
    name: "Vitamin D + Calcium Combo",
    type: "PACKAGE",
    category: "bone-joint",
    parameters: 2,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "The two most common bone-health checks, bundled together.",
    includes: ["Vitamin D Total", "Calcium"],
    basePrice: 999,
    baseMrp: 2400,
  },
  {
    slug: "rheumatoid-factor",
    name: "Rheumatoid Factor (RF)",
    type: "TEST",
    category: "bone-joint",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Screens for rheumatoid arthritis and other autoimmune joint conditions.",
    includes: ["Rheumatoid Factor"],
    basePrice: 449,
    baseMrp: 1000,
  },
  {
    slug: "uric-acid",
    name: "Uric Acid",
    type: "TEST",
    category: "bone-joint",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "Checks uric acid levels — elevated levels are linked to gout and kidney stones.",
    includes: ["Uric Acid"],
    basePrice: 199,
    baseMrp: 450,
  },
  {
    slug: "bone-health-package",
    name: "Bone Health Package",
    type: "PACKAGE",
    category: "bone-joint",
    parameters: 6,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "A complete bone-health panel covering the key minerals and markers of bone metabolism.",
    includes: ["Calcium", "Vitamin D Total", "Phosphorus", "Alkaline Phosphatase"],
    basePrice: 1399,
    baseMrp: 3400,
  },

  // ── Cancer Screening ──────────────────────────────────────────────────
  {
    slug: "psa-total",
    name: "PSA, Total (Prostate)",
    type: "TEST",
    category: "cancer-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    gender: "male",
    minAge: 40,
    description: "Screens for prostate conditions, including prostate cancer risk, in men over 40.",
    includes: ["PSA Total"],
    basePrice: 799,
    baseMrp: 1800,
  },
  {
    slug: "ca-125",
    name: "CA-125 (Ovarian Marker)",
    type: "TEST",
    category: "cancer-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    gender: "female",
    description: "A tumour marker used to help evaluate ovarian conditions, including ovarian cancer risk.",
    includes: ["CA-125"],
    basePrice: 1299,
    baseMrp: 3000,
  },
  {
    slug: "ca-15-3",
    name: "CA 15-3 (Breast Marker)",
    type: "TEST",
    category: "cancer-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    gender: "female",
    description: "A tumour marker used alongside imaging to help monitor breast cancer.",
    includes: ["CA 15-3"],
    basePrice: 1299,
    baseMrp: 3000,
  },
  {
    slug: "cea-tumor-marker",
    name: "CEA (Carcinoembryonic Antigen)",
    type: "TEST",
    category: "cancer-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "A general tumour marker, most often used to monitor colorectal cancer.",
    includes: ["CEA"],
    basePrice: 999,
    baseMrp: 2400,
  },
  {
    slug: "afp-tumor-marker",
    name: "AFP (Alpha-Fetoprotein)",
    type: "TEST",
    category: "cancer-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "A tumour marker used to help evaluate liver conditions, including liver cancer risk.",
    includes: ["AFP"],
    basePrice: 899,
    baseMrp: 2000,
  },

  // ── Allergy (more) ────────────────────────────────────────────────────
  {
    slug: "allergy-comprehensive-panel",
    name: "Allergy Comprehensive Panel (20 Allergens)",
    type: "PACKAGE",
    category: "allergy",
    parameters: 20,
    sampleType: "Blood",
    fasting: false,
    reportHours: 72,
    description: "A wide allergen screen covering common foods, dust, pollen and pet dander — for hard-to-pin-down allergies.",
    includes: ["Total IgE", "20 Food & Environmental Allergens"],
    basePrice: 2999,
    baseMrp: 7000,
  },
  {
    slug: "eosinophil-count",
    name: "Absolute Eosinophil Count",
    type: "TEST",
    category: "allergy",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    description: "A simple blood marker that rises with allergic conditions and parasitic infections.",
    includes: ["Absolute Eosinophil Count"],
    basePrice: 249,
    baseMrp: 550,
  },

  // ── STD/STI Screening ─────────────────────────────────────────────────
  {
    slug: "hiv-antibody",
    name: "HIV I & II Antibody",
    type: "TEST",
    category: "std-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "A confidential screening test for HIV — results are only ever visible to you, never shared.",
    includes: ["HIV I & II Antibody"],
    basePrice: 399,
    baseMrp: 900,
  },
  {
    slug: "vdrl-syphilis",
    name: "VDRL (Syphilis Screening)",
    type: "TEST",
    category: "std-screening",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    description: "Screens for syphilis infection.",
    includes: ["VDRL"],
    basePrice: 249,
    baseMrp: 550,
  },
  {
    slug: "std-comprehensive-panel",
    name: "STD Comprehensive Panel",
    type: "PACKAGE",
    category: "std-screening",
    parameters: 6,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    description: "A confidential, comprehensive screen for the most common sexually transmitted infections.",
    includes: ["HIV I & II", "VDRL (Syphilis)", "HBsAg", "Anti-HCV", "Herpes Simplex IgG"],
    basePrice: 2499,
    baseMrp: 6000,
  },

  // ── Pregnancy & Antenatal ─────────────────────────────────────────────
  {
    slug: "double-marker-test",
    name: "Double Marker Test",
    type: "TEST",
    category: "pregnancy",
    parameters: 2,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    gender: "female",
    description: "A first-trimester screening test for chromosomal conditions like Down syndrome.",
    includes: ["Free Beta hCG", "PAPP-A"],
    basePrice: 1999,
    baseMrp: 4500,
  },
  {
    slug: "triple-marker-test",
    name: "Triple Marker Test",
    type: "TEST",
    category: "pregnancy",
    parameters: 3,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    gender: "female",
    description: "A second-trimester screening test for chromosomal and neural tube conditions.",
    includes: ["AFP", "hCG", "Estriol"],
    basePrice: 1599,
    baseMrp: 3800,
  },
  {
    slug: "antenatal-profile-package",
    name: "Antenatal Profile Package",
    type: "PACKAGE",
    category: "pregnancy",
    parameters: 20,
    sampleType: "Blood + Urine",
    fasting: false,
    reportHours: 24,
    gender: "female",
    description: "The standard first-visit panel recommended for expecting mothers, in one booking.",
    includes: [
      "Complete Blood Count",
      "Blood Group & Rh Typing",
      "HIV, HBsAg, VDRL",
      "Thyroid Profile",
      "Fasting Blood Sugar",
      "Complete Urine Examination",
    ],
    basePrice: 1899,
    baseMrp: 4800,
  },
  {
    slug: "quadruple-marker-test",
    name: "Quadruple Marker Test",
    type: "TEST",
    category: "pregnancy",
    parameters: 4,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    gender: "female",
    description: "A second-trimester screen for Down syndrome and neural tube defects — an expanded version of the triple marker test with one extra marker for better accuracy.",
    includes: ["AFP", "hCG", "Estriol", "Inhibin-A"],
    basePrice: 2199,
    baseMrp: 5200,
  },
  {
    slug: "nipt-non-invasive-prenatal-testing",
    name: "NIPT (Non-Invasive Prenatal Testing)",
    type: "TEST",
    category: "pregnancy",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 168,
    gender: "female",
    minAge: 0,
    description: "A highly accurate screen for chromosomal conditions (like Down, Edwards and Patau syndrome) using cell-free fetal DNA from a simple maternal blood draw — safe, with no miscarriage risk unlike invasive tests.",
    includes: ["Fetal Trisomy 21/18/13 Risk", "Fetal Sex (optional)", "Sex Chromosome Aneuploidy Screen"],
    badge: "Advanced",
    basePrice: 13999,
    baseMrp: 22000,
  },
  {
    slug: "torch-panel",
    name: "TORCH Panel (IgG/IgM)",
    type: "PACKAGE",
    category: "pregnancy",
    parameters: 8,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    gender: "female",
    description: "Screens for infections — Toxoplasma, Rubella, Cytomegalovirus and Herpes — that can affect the baby if contracted during pregnancy.",
    includes: ["Toxoplasma IgG/IgM", "Rubella IgG/IgM", "CMV IgG/IgM", "HSV IgG/IgM"],
    basePrice: 2799,
    baseMrp: 6500,
  },
  {
    slug: "blood-group-rh-typing",
    name: "Blood Group & Rh Typing",
    type: "TEST",
    category: "pregnancy",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 6,
    description: "Determines ABO blood group and Rh factor — routinely required in pregnancy and before any surgery or transfusion.",
    includes: ["ABO Group", "Rh Factor"],
    basePrice: 149,
    baseMrp: 350,
  },
  {
    slug: "glucose-challenge-test",
    name: "Glucose Challenge Test (GCT)",
    type: "TEST",
    category: "pregnancy",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    gender: "female",
    description: "Screens for gestational diabetes, usually done between weeks 24–28 of pregnancy.",
    includes: ["1-Hour Post-Glucose-Load Sugar"],
    basePrice: 249,
    baseMrp: 600,
  },
  {
    slug: "thalassemia-screening-hplc",
    name: "Thalassemia Screening (HPLC)",
    type: "TEST",
    category: "pregnancy",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    description: "Screens for thalassemia trait — recommended for couples planning a pregnancy or in early pregnancy.",
    includes: ["Hemoglobin Electrophoresis (HPLC)"],
    basePrice: 899,
    baseMrp: 2000,
  },
  {
    slug: "rubella-igg-igm",
    name: "Rubella IgG/IgM",
    type: "TEST",
    category: "pregnancy",
    parameters: 2,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    gender: "female",
    description: "Checks for rubella immunity or active infection — rubella during pregnancy can seriously affect the baby.",
    includes: ["Rubella IgG", "Rubella IgM"],
    basePrice: 899,
    baseMrp: 2000,
  },

  // ── Executive Checkup ─────────────────────────────────────────────────
  {
    slug: "executive-health-checkup",
    name: "Executive Health Checkup",
    type: "PACKAGE",
    category: "executive",
    parameters: 120,
    sampleType: "Blood + Urine",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description: "A comprehensive annual checkup built for busy professionals — covers heart, diabetes, liver, kidney, thyroid, cancer markers and more in a single visit.",
    includes: [
      "Full Body Checkup — Advanced",
      "Cardiac Risk Package",
      "PSA / CA-125",
      "ECG",
      "Iron Studies",
    ],
    badge: "Comprehensive",
    basePrice: 2999,
    baseMrp: 9500,
  },
  {
    slug: "master-health-checkup",
    name: "Master Health Checkup",
    type: "PACKAGE",
    category: "executive",
    parameters: 150,
    sampleType: "Blood + Urine",
    fasting: true,
    fastingHours: 10,
    reportHours: 24,
    description: "Our most complete checkup — every major organ system, hormone panel and cancer marker screened in one visit.",
    includes: [
      "Executive Health Checkup",
      "Thyroid Antibodies Panel",
      "Vitamin B-Complex",
      "Bone Health Package",
      "Allergy Basic Panel",
    ],
    badge: "Most Complete",
    basePrice: 3999,
    baseMrp: 12000,
  },
  {
    slug: "newborn-screening-panel",
    name: "Newborn Screening Panel",
    type: "PACKAGE",
    category: "child-care",
    parameters: 5,
    sampleType: "Blood",
    fasting: false,
    reportHours: 48,
    minAge: 0,
    description: "Early screening for treatable congenital disorders in newborns — thyroid, metabolic and enzyme conditions.",
    includes: ["TSH (Newborn)", "PKU (Phenylketonuria)", "G6PD", "Galactosemia Screen", "CAH Screen"],
    popular: true,
    badge: "For Newborns",
    basePrice: 1299,
    baseMrp: 2800,
  },
  {
    slug: "child-growth-nutrition-panel",
    name: "Child Growth & Nutrition Panel",
    type: "PACKAGE",
    category: "child-care",
    parameters: 15,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    minAge: 1,
    description: "Checks the vitamin, mineral and blood markers most linked to a child's growth, energy and development.",
    includes: ["Vitamin D", "Vitamin B12", "Calcium", "Iron Studies", "Complete Blood Count"],
    popular: true,
    basePrice: 1499,
    baseMrp: 3200,
  },
  {
    slug: "pediatric-fever-panel",
    name: "Pediatric Fever Panel",
    type: "PACKAGE",
    category: "child-care",
    parameters: 10,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    minAge: 1,
    description: "Common childhood fever workup — screens for the usual infectious causes in one home visit instead of several.",
    includes: ["Complete Blood Count", "CRP", "Malaria Antigen", "Dengue NS1", "Widal Test"],
    basePrice: 899,
    baseMrp: 2000,
  },
  {
    slug: "stool-routine-examination",
    name: "Stool Routine Examination (Worm Infestation)",
    type: "TEST",
    category: "child-care",
    parameters: 8,
    sampleType: "Stool",
    fasting: false,
    reportHours: 12,
    minAge: 0,
    description: "Checks a stool sample for intestinal worms and parasites — one of the most common childhood lab tests.",
    includes: ["Ova & Cysts", "Occult Blood", "Consistency", "Mucus", "pH"],
    popular: true,
    basePrice: 199,
    baseMrp: 450,
  },
  {
    slug: "iron-deficiency-screening-child",
    name: "Iron Deficiency Screening — Child",
    type: "TEST",
    category: "child-care",
    parameters: 3,
    sampleType: "Blood",
    fasting: false,
    reportHours: 12,
    minAge: 1,
    description: "Checks haemoglobin and iron stores — the most common cause of fatigue, poor appetite and pica in young children.",
    includes: ["Haemoglobin", "Serum Ferritin", "Total Iron Binding Capacity"],
    basePrice: 549,
    baseMrp: 1200,
  },
  {
    slug: "aso-titre",
    name: "ASO Titre (Post-Strep Screening)",
    type: "TEST",
    category: "child-care",
    parameters: 1,
    sampleType: "Blood",
    fasting: false,
    reportHours: 24,
    minAge: 2,
    description: "Checks for a recent strep throat infection — relevant for children with recurring sore throats or joint pain.",
    includes: ["Anti-Streptolysin O"],
    basePrice: 449,
    baseMrp: 950,
  },
];

// Longer "what is this test & what it's used for" copy shown on the product
// page before the price comparison — keyed by slug, separate from the short
// `description` one-liner used as the card/meta subtitle. Falls back to the
// short description if a slug is missing here.
const ABOUT: Record<string, string> = {
  "complete-blood-count":
    "A Complete Blood Count is one of the most commonly ordered blood tests — it measures your red blood cells, white blood cells and platelets in one go. Doctors use it to screen for anaemia, infections, clotting problems and a range of general blood disorders, and it's often the first test ordered when you're feeling unwell or during a routine checkup.",
  hba1c:
    "HbA1c measures the percentage of haemoglobin coated with sugar, which reflects your average blood glucose over the past 2–3 months rather than a single point in time. It's the gold-standard test for diagnosing diabetes and monitoring how well existing diabetes is controlled, and unlike a fasting sugar test, you don't need to fast for it.",
  "fasting-blood-sugar":
    "Fasting Blood Sugar measures your glucose level after at least 8 hours without food, giving a snapshot of how your body regulates sugar at rest. It's a standard first-line test for screening diabetes and pre-diabetes, and is often repeated alongside HbA1c for a fuller picture.",
  "thyroid-profile-total":
    "This panel measures T3, T4 and TSH — the three hormones that control your thyroid gland's activity. It's used to diagnose an underactive thyroid (hypothyroidism, which can cause fatigue and weight gain) or an overactive one (hyperthyroidism, linked to weight loss and rapid heartbeat), and is commonly ordered when someone reports unexplained fatigue, weight changes or mood swings.",
  "lipid-profile":
    "A Lipid Profile measures total cholesterol, HDL (\"good\" cholesterol), LDL (\"bad\" cholesterol), VLDL and triglycerides. It's the standard test for assessing your risk of heart disease and stroke, and is usually recommended annually for adults, more often if you have a family history of heart disease, diabetes, or are overweight. An overnight fast is recommended for accurate results.",
  "liver-function-test":
    "A Liver Function Test checks enzymes like SGOT and SGPT along with bilirubin and protein levels to assess how well your liver is working. It's used to detect liver damage from causes like hepatitis, alcohol use, fatty liver disease or medication side effects, and is often ordered alongside routine health checkups or before starting certain long-term medications.",
  "kidney-function-test":
    "A Kidney Function Test measures creatinine, urea, uric acid and electrolyte levels to evaluate how well your kidneys are filtering waste from your blood. It's commonly used to screen for chronic kidney disease, monitor existing kidney conditions, or check kidney health before starting medications that are processed by the kidneys.",
  "vitamin-d-total":
    "This test measures 25-hydroxy Vitamin D, the storage form of Vitamin D in your blood. Deficiency is extremely common, especially with limited sun exposure, and is linked to weak bones, muscle pain, fatigue and a weakened immune system — this test is used to confirm a deficiency so it can be corrected with supplements.",
  "vitamin-b12":
    "Vitamin B12 is essential for nerve function and the production of healthy red blood cells. This test checks for deficiency, which is common in vegetarians, vegans and older adults, and can cause fatigue, numbness/tingling, memory issues and a specific type of anaemia if left untreated.",
  "complete-urine-examination":
    "A Complete Urine Examination checks the physical, chemical and microscopic properties of your urine — including protein, glucose, pus cells and specific gravity. It's used to screen for urinary tract infections, kidney disorders, diabetes and dehydration, and is a routine part of most general health checkups.",
  "dengue-ns1":
    "The Dengue NS1 Antigen test detects a specific dengue virus protein that appears in the blood from day 1 of fever, making it useful for early diagnosis before antibody-based tests would show a positive result. It's typically ordered when someone has fever, body aches and other symptoms during dengue season.",
  "widal-test":
    "The Widal Test detects antibodies against Salmonella typhi, the bacteria that causes typhoid fever. It's commonly ordered for patients with prolonged fever, especially after the first week of illness, though results are usually interpreted alongside symptoms since past typhoid infections or vaccination can also affect readings.",
  "full-body-essential":
    "A broad screening package covering blood counts, sugar, lipids, liver, kidney and thyroid function in one visit. It's designed for anyone who wants a general health snapshot without needing to book multiple individual tests — a good starting point for an annual checkup.",
  "full-body-advanced":
    "A more comprehensive version of our essential checkup, adding vitamin levels, additional cardiac markers and a wider hormone panel. It suits anyone wanting a deeper, more complete picture of their overall health in a single booking.",
  "diabetes-screening":
    "A package that combines fasting sugar, HbA1c and related markers to both screen for diabetes and monitor it if you're already diagnosed. Recommended for anyone with a family history of diabetes, unexplained weight change, or routine annual monitoring.",
  "heart-health":
    "Combines a lipid profile with additional cardiac risk indicators to give a fuller picture of your heart disease risk than a lipid test alone. Suited to anyone with a family history of heart disease, high blood pressure, or those wanting proactive cardiac screening.",
  "womens-wellness":
    "A package built around the health markers most relevant to women — hormones, thyroid, iron levels, bone health and general wellness — in one booking instead of several separate tests.",
  "thyroid-vitamin-combo":
    "Bundles a full thyroid panel with Vitamin D and B12, the two most commonly deficient vitamins, since fatigue and low energy can stem from either — checking all three together helps pinpoint the actual cause.",
  "senior-citizen-checkup":
    "A checkup package tailored for adults above 60, covering the systems that need closer monitoring with age — heart, bones, kidneys, liver and diabetes risk — in a single visit designed to reduce the number of separate tests needed.",
  "fever-panel":
    "Combines the most common fever-cause tests — including dengue, typhoid and a complete blood count — so the likely cause of a prolonged or unexplained fever can be narrowed down in one sample instead of several separate bookings.",
  "allergy-basic-panel":
    "Screens for common allergens through a blood-based IgE test, useful for identifying triggers behind recurring symptoms like sneezing, skin rashes or itching when the cause isn't obvious.",
  "post-prandial-blood-sugar":
    "Post Prandial Blood Sugar measures glucose roughly 2 hours after a meal, showing how well your body manages a sugar load — a useful complement to fasting sugar for a fuller diabetes picture, especially when fasting levels are borderline.",
  "glucose-tolerance-test":
    "The Glucose Tolerance Test measures how your body processes sugar over time by testing blood glucose before and after drinking a glucose solution. It's commonly used to diagnose gestational diabetes in pregnant women and to confirm diabetes when fasting/random sugar results are inconclusive.",
  "insulin-fasting":
    "Fasting Insulin measures the insulin hormone level in your blood after fasting, used alongside glucose tests to assess insulin resistance — often relevant for PCOS, pre-diabetes or unexplained weight gain.",
  "ecg-resting":
    "A resting ECG records your heart's electrical activity to check for irregular heart rhythms, signs of a previous heart attack, or other cardiac abnormalities. It's quick, painless and often part of routine cardiac screening or pre-checkup evaluations.",
  "troponin-i":
    "Troponin I is a protein released into the blood when heart muscle is damaged. This test is used to detect or rule out a heart attack, particularly in someone experiencing chest pain, and is typically ordered urgently rather than as routine screening.",
  homocysteine:
    "Homocysteine is an amino acid that, at elevated levels, is linked to increased risk of heart disease and stroke. This test is used as part of a broader cardiac risk assessment, especially when there's a family history of early heart disease.",
  "cardiac-risk-package":
    "A focused panel combining lipid profile, ECG-linked markers and inflammation indicators to give a rounder view of heart disease risk than any single test alone — useful for anyone with risk factors like family history, smoking or high blood pressure.",
  "tsh-only":
    "TSH is the hormone that signals your thyroid gland to produce T3 and T4. Testing it alone is often the first step in thyroid screening — an abnormal result usually leads to a fuller thyroid panel to pinpoint whether the thyroid is under- or overactive.",
  "thyroid-antibodies-panel":
    "This panel checks for Anti-TPO and Anti-TG antibodies, which attack the thyroid gland in autoimmune thyroid conditions like Hashimoto's thyroiditis and Graves' disease. It's ordered when standard thyroid hormone results are abnormal and an autoimmune cause is suspected.",
  "vitamin-a":
    "Vitamin A (Retinol) supports vision, immune function and skin health. This test checks for deficiency or excess, relevant for people with night vision problems, dry skin, or recurring infections.",
  "folic-acid":
    "Folic Acid (Folate) is essential for cell growth and red blood cell production. This test checks for deficiency, which can cause a type of anaemia and is particularly important to rule out during pregnancy planning, since low folate is linked to birth defects.",
  "vitamin-b-complex-package":
    "Covers the key B-vitamins together — including B12, folate and others — useful when fatigue, nerve symptoms or dietary gaps make it worth checking the whole group rather than one vitamin at a time.",
  "hepatitis-b-surface-antigen":
    "This test detects the surface antigen of the Hepatitis B virus, indicating active infection. It's used to diagnose Hepatitis B, screen before certain medical procedures or vaccinations, and is often required during pregnancy checkups and pre-employment screenings.",
  "hepatitis-c-antibody":
    "This test detects antibodies against the Hepatitis C virus, indicating current or past infection. It's used to screen for Hepatitis C, particularly for anyone with risk factors like a history of blood transfusion or intravenous exposure, or unexplained liver enzyme abnormalities.",
  "urine-microalbumin":
    "Urine Microalbumin detects small amounts of protein in urine that standard urine tests can miss — an early warning sign of kidney damage, particularly important for people with diabetes or high blood pressure to catch kidney involvement early.",
  "kidney-stone-risk-panel":
    "Checks the blood and urine markers linked to kidney stone formation — including calcium, uric acid and oxalate-related factors — useful for anyone with a personal or family history of kidney stones.",
  "malaria-antigen":
    "The Malaria Antigen Test detects malaria parasite proteins in the blood, giving a fast result for diagnosing malaria in someone with fever, chills and other suggestive symptoms, especially during monsoon season.",
  "covid19-rtpcr":
    "RT-PCR remains the most accurate test for detecting active COVID-19 infection, identifying the virus's genetic material from a nasal/throat swab. Used for diagnosis when symptomatic, for travel requirements, or after known exposure.",
  "chikungunya-igm":
    "This test detects IgM antibodies against the Chikungunya virus, which typically appear about a week into the illness. It's ordered for fever accompanied by severe joint pain, particularly during outbreak season.",
  "crp-quantitative":
    "C-Reactive Protein (CRP) is produced by the liver in response to inflammation anywhere in the body. This quantitative test is used to detect and monitor inflammation or infection, and elevated levels can also be a marker for cardiovascular risk.",
  "pcos-panel":
    "A hormone panel used to help diagnose Polycystic Ovary Syndrome (PCOS), a common condition affecting periods, fertility and metabolism. Typically ordered for irregular periods, excess hair growth, acne or difficulty conceiving.",
  "pregnancy-test-beta-hcg":
    "This blood test measures Beta hCG, the hormone produced during pregnancy, and can confirm pregnancy earlier and more precisely than a urine test — the quantitative result can also help track how a pregnancy is progressing in its early weeks.",
  "amh-ovarian-reserve":
    "Anti-Müllerian Hormone (AMH) reflects a woman's remaining egg supply (ovarian reserve). It's commonly used in fertility assessments and family planning discussions, particularly for women considering when to conceive or undergoing fertility treatment.",
  "pap-smear":
    "A Pap Smear screens for abnormal cervical cells that could indicate a risk of cervical cancer, well before symptoms appear. Routine screening is recommended for sexually active women, typically starting in their 20s and repeated every few years.",
  "senior-cardiac-package":
    "A cardiac-focused package for older adults, combining ECG, lipid profile and related markers to catch heart disease risk early — recommended as part of regular senior health monitoring.",
  "iron-studies":
    "Iron Studies measure iron, ferritin and related markers to diagnose iron-deficiency anaemia or, less commonly, iron overload. Commonly ordered for fatigue, pale skin, or unexplained anaemia found on a routine blood count.",
  "electrolytes-panel":
    "Measures sodium, potassium and other electrolytes that keep your nerves, muscles and heart functioning normally. Ordered when someone has symptoms like muscle weakness, irregular heartbeat, or as part of monitoring certain medications and kidney conditions.",
  "esr-test":
    "ESR (Erythrocyte Sedimentation Rate) is a simple, nonspecific test that indicates inflammation somewhere in the body. It's used alongside other tests to help diagnose or monitor inflammatory conditions, infections or autoimmune diseases.",
  "calcium-total":
    "Measures total calcium in the blood, important for bones, muscles and nerve function. Used to investigate bone health, parathyroid or kidney issues, or symptoms like muscle cramps and fatigue.",
  "vitamin-d-calcium-combo":
    "Combines Vitamin D and Calcium testing since the two work together for bone health — useful for anyone investigating bone pain, muscle weakness, or as part of routine bone health monitoring, especially in older adults.",
  "rheumatoid-factor":
    "Rheumatoid Factor is an antibody test used to help diagnose rheumatoid arthritis and other autoimmune conditions, typically ordered when someone has persistent joint pain, swelling or stiffness.",
  "uric-acid":
    "Measures uric acid levels in the blood, high levels of which cause gout (painful joint inflammation) and are linked to kidney stones. Ordered for joint pain, swelling, or as part of monitoring known gout or kidney stone history.",
  "bone-health-package":
    "Combines calcium, Vitamin D and related bone markers to give a fuller picture of bone health — useful for anyone concerned about bone density, fracture risk, or as part of monitoring osteoporosis risk with age.",
  "psa-total":
    "PSA (Prostate-Specific Antigen) is a screening test for prostate health, with elevated levels potentially indicating prostate enlargement, inflammation, or cancer. Commonly recommended for men above 50, or earlier with a family history of prostate cancer.",
  "ca-125":
    "CA-125 is a protein that can be elevated with ovarian cancer, though also with several benign conditions — it's used as part of ovarian cancer screening/monitoring, particularly for women with a family history or existing symptoms, rather than as a standalone diagnostic test.",
  "ca-15-3":
    "CA 15-3 is a tumour marker most useful for monitoring known breast cancer treatment response rather than as a first-line screening test, since it can also be mildly elevated in benign conditions.",
  "cea-tumor-marker":
    "CEA (Carcinoembryonic Antigen) is a tumour marker most commonly used to monitor colorectal cancer treatment and detect recurrence, and can be mildly elevated by smoking or other non-cancerous conditions.",
  "afp-tumor-marker":
    "AFP (Alpha-Fetoprotein) is used as a tumour marker for liver cancer screening/monitoring in at-risk individuals, and separately as part of prenatal screening for certain fetal conditions when tested during pregnancy.",
  "allergy-comprehensive-panel":
    "A wider IgE-based allergy panel screening 20 common allergens — foods, dust, pollen and more — useful when symptoms are persistent or the basic panel hasn't identified a clear trigger.",
  "eosinophil-count":
    "Measures eosinophils, a type of white blood cell that rises with allergic reactions and parasitic infections. Ordered when allergy symptoms, asthma, or suspected parasitic infection need further investigation.",
  "hiv-antibody":
    "Detects antibodies against HIV I and II, used for HIV screening. Testing is confidential and recommended as routine screening, before certain procedures, during pregnancy, or after potential exposure.",
  "vdrl-syphilis":
    "VDRL is a screening test for syphilis, a sexually transmitted infection. Commonly required during pregnancy checkups, pre-marital screening, or when symptoms suggest a possible STI.",
  "std-comprehensive-panel":
    "A combined panel screening for multiple sexually transmitted infections in one booking, useful for routine sexual health screening or after a potential exposure, with the privacy of one home visit instead of several.",
  "double-marker-test":
    "The Double Marker Test is a first-trimester prenatal screening test (done between weeks 11–13) that assesses the risk of Down syndrome and other chromosomal conditions, usually combined with an ultrasound (NT scan) for a fuller risk assessment.",
  "triple-marker-test":
    "The Triple Marker Test is a second-trimester prenatal screening test assessing risk of Down syndrome, Edward's syndrome and neural tube defects, done when a first-trimester screen wasn't performed or as an additional check.",
  "antenatal-profile-package":
    "A bundled panel of the standard blood tests recommended during pregnancy — including blood group, infections screening and general health markers — covering routine antenatal checkup requirements in one booking.",
  "quadruple-marker-test":
    "The Quadruple Marker Test is a second-trimester prenatal screening test (ideally done between weeks 15–20) that measures four blood markers to assess the risk of Down syndrome, Edward's syndrome and open neural tube defects. It's a screening test, not diagnostic — a higher-risk result is typically followed by further diagnostic tests like amniocentesis.",
  "nipt-non-invasive-prenatal-testing":
    "NIPT analyses fetal DNA fragments present in the mother's blood to screen for chromosomal conditions like Down syndrome with high accuracy, without any risk to the pregnancy — usually done from week 10 onwards as a more sensitive alternative to standard marker tests.",
  "torch-panel":
    "The TORCH Panel screens for a group of infections (Toxoplasma, Other agents, Rubella, CMV, Herpes) that can affect a developing fetus if the mother is infected during pregnancy — typically ordered when planning a pregnancy or after unusual pregnancy symptoms.",
  "blood-group-rh-typing":
    "Determines your ABO blood group and Rh factor — required during pregnancy to check for Rh incompatibility risk between mother and baby, and generally useful to have on record for any future medical or surgical need.",
  "glucose-challenge-test":
    "The Glucose Challenge Test is a screening test for gestational diabetes, typically done between weeks 24–28 of pregnancy, measuring blood sugar response after a glucose drink.",
  "thalassemia-screening-hplc":
    "HPLC-based Thalassemia Screening detects abnormal haemoglobin patterns linked to thalassemia, a genetic blood disorder — commonly recommended before or during pregnancy, or when a routine blood count shows unexplained anaemia patterns.",
  "rubella-igg-igm":
    "Checks for Rubella (German Measles) immunity or active infection through IgG and IgM antibodies — important during pregnancy planning, since a Rubella infection during pregnancy can seriously affect the developing baby.",
  "executive-health-checkup":
    "A comprehensive checkup designed for working professionals, covering the major organ systems, metabolic markers and lifestyle-risk indicators in a single visit built around a busy schedule.",
  "master-health-checkup":
    "Our most complete health checkup, combining major organ function tests, hormone panels, vitamin levels, bone health and cancer marker screening in one visit — built for anyone wanting the fullest possible picture of their health in a single booking.",
  "newborn-screening-panel":
    "Newborn screening checks a small blood sample for a handful of rare but serious congenital conditions — thyroid deficiency, PKU, G6PD deficiency and metabolic disorders — that show no symptoms at birth but are far more manageable when caught in the first weeks of life rather than found later.",
  "child-growth-nutrition-panel":
    "A panel built around the deficiencies that most commonly show up as poor growth, low energy or frequent illness in children — Vitamin D, B12, iron and calcium levels alongside a complete blood count — useful whenever a child seems to be falling behind on growth or energy without an obvious cause.",
  "pediatric-fever-panel":
    "Combines the most common childhood fever-cause tests — including dengue, malaria, typhoid and a complete blood count with CRP — so the likely cause of a child's fever can be narrowed down from one home visit instead of several separate bookings.",
  "stool-routine-examination":
    "A stool sample examined for intestinal worms, parasites and signs of infection — one of the most frequently recommended tests in childhood, especially for recurring stomach pain, poor appetite, or itching, and often repeated periodically as routine deworming follow-up.",
  "iron-deficiency-screening-child":
    "Checks haemoglobin and iron stores specifically for children, where iron deficiency is common and shows up as tiredness, poor concentration, pale skin, or unusual cravings like eating chalk or ice (pica) — catching it early makes correcting it with diet or supplements much easier.",
  "aso-titre":
    "ASO (Anti-Streptolysin O) Titre checks for antibodies from a recent Streptococcus throat infection. It's mainly used in children with frequent sore throats or joint pain, since untreated repeated strep infections are linked to rheumatic fever — a preventable but serious complication.",
};

// Per-lab price multipliers relative to the base price, tuned so it's not
// always Jammu Genetics Hub that wins — a believable comparison table.
const labMultipliers: Record<string, { price: number; mrp: number }> = {
  "jammu-genetics-hub": { price: 1.0, mrp: 1.0 },
  thyrocare: { price: 1.08, mrp: 0.95 },
  "redcliffe-labs": { price: 1.15, mrp: 1.05 },
  "dr-lal-pathlabs": { price: 1.35, mrp: 1.3 },
  metropolis: { price: 1.28, mrp: 1.2 },
};

function jitter(n: number, seed: number) {
  // deterministic small variation so prices don't look mechanically identical
  const factor = 1 + (((seed * 37) % 11) - 5) / 100;
  return Math.round((n * factor) / 10) * 10 - 1; // end in a charm price like x99
}

async function main() {
  console.log("Seeding labs...");
  const labRecords: Record<string, string> = {};
  for (const lab of labs) {
    const rec = await prisma.lab.upsert({
      where: { slug: lab.slug },
      update: lab,
      create: lab,
    });
    labRecords[lab.slug] = rec.id;
  }

  console.log("Seeding categories...");
  const categoryRecords: Record<string, string> = {};
  for (const cat of categories) {
    const rec = await prisma.category.upsert({
      where: { slug: cat.slug },
      update: cat,
      create: cat,
    });
    categoryRecords[cat.slug] = rec.id;
  }

  console.log("Seeding products & prices...");
  let seedIndex = 0;
  for (const p of products) {
    seedIndex++;
    const about = ABOUT[p.slug] ?? p.description;
    const product = await prisma.product.upsert({
      where: { slug: p.slug },
      update: {
        name: p.name,
        type: p.type,
        categoryId: categoryRecords[p.category],
        parameters: p.parameters,
        sampleType: p.sampleType,
        fasting: p.fasting,
        fastingHours: p.fastingHours,
        reportHours: p.reportHours,
        gender: p.gender ?? "both",
        minAge: p.minAge ?? 0,
        description: p.description,
        about,
        includesJson: JSON.stringify(p.includes),
        popular: p.popular ?? false,
        badge: p.badge,
      },
      create: {
        slug: p.slug,
        name: p.name,
        type: p.type,
        categoryId: categoryRecords[p.category],
        parameters: p.parameters,
        sampleType: p.sampleType,
        fasting: p.fasting,
        fastingHours: p.fastingHours,
        reportHours: p.reportHours,
        gender: p.gender ?? "both",
        minAge: p.minAge ?? 0,
        description: p.description,
        about,
        includesJson: JSON.stringify(p.includes),
        popular: p.popular ?? false,
        badge: p.badge,
      },
    });

    // On roughly 1 in 3 products, price JGH slightly above its usual mark so a
    // competitor sometimes wins the comparison — an honest aggregator table,
    // not one that mechanically always favours the house lab.
    const jghHandicap = seedIndex % 3 === 0 ? 1.1 : 1.0;

    let labIndex = 0;
    for (const lab of labs) {
      labIndex++;
      const mult = labMultipliers[lab.slug];
      // Specialty genetic-testing partner labs (AMPATH, Tata 1mg, MedGenome,
      // Yoda, Lilac Insights) don't price routine commodity tests at all —
      // they only get prices via the sparse, real-data GENETIC_PRODUCTS
      // seeding below, not this jitter-based fabrication loop.
      if (!mult) continue;
      const ownAdjust = lab.isOwn ? jghHandicap : 1.0;
      const price = jitter(p.basePrice * mult.price * ownAdjust, seedIndex * 7 + labIndex);
      const mrp = Math.max(price + 100, Math.round((p.baseMrp * mult.mrp) / 10) * 10);
      await prisma.price.upsert({
        where: { productId_labId: { productId: product.id, labId: labRecords[lab.slug] } },
        update: { price, mrp },
        create: { productId: product.id, labId: labRecords[lab.slug], price, mrp },
      });
    }
  }

  console.log("Seeding genetic/specialty tests (real partner data)...");
  for (const g of GENETIC_PRODUCTS) {
    const product = await prisma.product.upsert({
      where: { slug: g.slug },
      update: {
        name: g.name,
        type: g.type,
        categoryId: categoryRecords[g.category],
        parameters: g.parameters,
        sampleType: g.sampleType,
        fasting: g.fasting,
        reportHours: g.reportHours,
        gender: g.gender ?? "both",
        minAge: g.minAge ?? 0,
        description: g.description,
        about: g.about,
        includesJson: JSON.stringify(g.includes),
        popular: g.popular ?? false,
        badge: g.badge,
      },
      create: {
        slug: g.slug,
        name: g.name,
        type: g.type,
        categoryId: categoryRecords[g.category],
        parameters: g.parameters,
        sampleType: g.sampleType,
        fasting: g.fasting,
        reportHours: g.reportHours,
        gender: g.gender ?? "both",
        minAge: g.minAge ?? 0,
        description: g.description,
        about: g.about,
        includesJson: JSON.stringify(g.includes),
        popular: g.popular ?? false,
        badge: g.badge,
      },
    });

    // JGH's own price — the only one we set a policy for; every partner
    // price below is real data, taken as-is (no invented markup/mrp).
    await prisma.price.upsert({
      where: { productId_labId: { productId: product.id, labId: labRecords["jammu-genetics-hub"] } },
      update: { price: g.jghPrice, mrp: g.jghMrp, testCode: null },
      create: { productId: product.id, labId: labRecords["jammu-genetics-hub"], price: g.jghPrice, mrp: g.jghMrp },
    });

    for (const p of g.partners) {
      await prisma.price.upsert({
        where: { productId_labId: { productId: product.id, labId: labRecords[p.labSlug] } },
        update: { price: p.price, mrp: p.mrp, testCode: p.testCode },
        create: { productId: product.id, labId: labRecords[p.labSlug], price: p.price, mrp: p.mrp, testCode: p.testCode },
      });
    }

    // A handful of these slugs already existed from earlier seeding (with
    // fabricated prices at the original 4 comparison labs) — remove any
    // lab price not in this real, sparse partner list so nothing fake is
    // left sitting next to the real data.
    const keepLabIds = [labRecords["jammu-genetics-hub"], ...g.partners.map((p) => labRecords[p.labSlug])];
    await prisma.price.deleteMany({ where: { productId: product.id, labId: { notIn: keepLabIds } } });
  }

  console.log("Seeding coupons...");
  await prisma.coupon.upsert({
    where: { code: "WELCOME15" },
    update: { audience: "NEW_USER", firstOrderOnly: true },
    create: {
      code: "WELCOME15",
      description: "15% off your first booking, up to ₹400",
      type: "PERCENT",
      value: 15,
      maxDiscount: 400,
      minOrderAmount: 0,
      audience: "NEW_USER",
      firstOrderOnly: true,
      active: true,
    },
  });

  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
